### ISSUE TITLE
[module]: ledger

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#10]

**Comment by matthiasbeyer** [comment]
As far as I can tell by now, including [beancount](http://furius.ca/beancount/) would be preferable over including [ledger-cli](http://ledger-cli.org/) or [hledger](http://hledger.org/), as the former is _way_ better documented, reliable and supports plugin, which the latter two do not.

beancount has a smaller user base due to [plaintextaccounting.org](http://plaintextaccounting.org/), but as far as I can see from the docs it fits our needs better.

Of course, more investigation has to be made so we can be sure how to proceed on this.

**Comment by johannesjh** [comment]
Hi Mattias, I think you should consider discussing your ideas at ledger-cli@googlegroups.com. I have myself asked a few questions there and I always got friendly, helpful and motivated answers. 

As a sidenote, I stumbled upon the imag tool when I was searching for a way to integrate (link, track...) beancount data with todos or even workflow-oriented data for tracking invoices. Beancount proposes to use links or tags to group transactions related to an invoice together. It also has a `document' statement to link to PDFs, e.g., to the invoice sent to the customer. But, from what I know, it does not have features for tracking the status of an invoice (e.g., draft, to be payed, payed, closed, cancelled etc). Would this use case be something where imag can provide value by integrating something like taskwarrior with beancount?

Johannes

**Comment by matthiasbeyer** [comment]
Hi!

Yes, I use beancount myself and you're absolutely correct from what I see and yes, imag could provide functionality (no, it actually _would_ provide this functionality, as soon as it is implemented) you mentioned.
With imag, you could link tasks from taskwarrior to beancount, could add notes to transactions in beancount and so on.

Currently, we're doing a focus-transition (see #846) because the scope is too much for me, my masters courses are a hell of a job to do and having a ruby library which can talk to imag would speed things up a lot.

So to sum up: Yes!
