### ISSUE TITLE
Implement: Store::delete()

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#106]

**Comment by matthiasbeyer** [comment]
@neithernut Wanna do this?

**Comment by neithernut** [comment]
Sure.

**Comment by neithernut** [comment]
This issue can now be closed (I'll use `resolves #...` next time)

**Comment by matthiasbeyer** [comment]
@neithernut Just use "Closes #...", but in the _pull request description_. Not in the commits please!

**Comment by neithernut** [comment]
Of course not.
