### ISSUE TITLE
remove `imag-counter` and `libimagcounter`

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#1114]
It was a showcase how to write imag applications. Now it is rather useless.

@mario-kr @TheNeikos what do you think? Remove it?

**Comment by mario-kr** [comment]
I don't mind either way, there are already some implementations where you could point new contributors to.

**Comment by matthiasbeyer** [comment]
Then it is agreed upon this: I will remove imag-counter for the next release.
