### ISSUE TITLE
[store]: Behaviour if store-path does not exist?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#112]
What is the behaviour if the path, passed to `Store::new()` does not exist?

Is it implicitely created? Is an error raised?

With the current interface, I'd guess that it is created, though I'd propose to change the interface to:

```rs
impl Store {
    fn new(PathBuf) -> Result<Store, StoreError>;
    fn create(PathBuf) -> Store;
    // ...
}
```

for more clearity.

**Comment by neithernut** [comment]
I agree with you, but `new` is not really intuitive. I'd suggest:
```
impl Store {
    fn open(PathBuf) -> Result<Store, StoreError>;
    fn create(PathBuf) -> Store;
    // ...
}
```

**Comment by matthiasbeyer** [comment]
Ok. I will implement this.

**Comment by TheNeikos** [comment]
I think that it should create it. `new` is Rusty and shouldn't really be deviated from.

**Comment by matthiasbeyer** [comment]
@TheNeikos good point.

**Comment by matthiasbeyer** [comment]
What happens if the path exists, but is a file?

**Comment by neithernut** [comment]
Error

**Comment by matthiasbeyer** [comment]
So we change `::new()` to

```rs
fn new() -> Result<Store, StoreError>;
```

?

**Comment by neithernut** [comment]
Mh... this does indeed break the convention IMO.

**Comment by matthiasbeyer** [comment]
I assume we have to do it that way.
