### ISSUE TITLE
Shell completion for imag binary itself

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#1211]
Currently, the bash completion for the `imag` binary itself only knows of the flags created via clap.

We have no way to complete the following:

```
imag --rtp /tmp diary <tab>
```

because this would need the script to call the completion script of `imag-diary` in this case.

Maybe @mario-kr or even @manuelmessner (our shell/bash guru) knows a solution for this.

Completion scripts can be generated via `<imag tool> --generate-commandline-completion <shell>` where `shell` is one of `bash`, `fish`, or `zsh`.

**Comment by matthiasbeyer** [comment]
Ah, let me ping @kbknapp here as well, maybe this issue comes up somewhere else as well...

**Comment by matthiasbeyer** [comment]
Just let me drop this here, could be a useful read: https://hackaday.com/2018/01/19/linux-fu-custom-bash-command-completion/

**Comment by kbknapp** [comment]
> `imag --rtp /tmp diary <tab>`

Where the script needs to come from `imag-diary`, this is something where you may have to edit the script generated by clap. I.e. for the `diary` (or subcommand position) in the background call the `imag-tool --generate-command-line-completion <shell>` which I know at least Bash (and probably Zsh) support although I'm not *super* familiar with the "dynamic" completion like that.

**Comment by matthiasbeyer** [comment]
@manuelmessner wanna tackle this issue?

**Comment by kbknapp** [comment]
I wish I had time to, but I barely have time to try and work on clap and get clap v3 out the door :disappointed: . However, if I do come across some spare time I'll take a look at this issue and see if I can at least provide some more guidance on how to tackle it.
