### ISSUE TITLE
Introduction>The Problem: wrong statement related to the underlying situation

### ISSUE THREAD

**Issue by novoid** [matthiasbeyer/imag#1230]
Hi,

On https://github.com/matthiasbeyer/imag/blob/master/doc/src/01000-intro.md the project states that:

> The problem imag wants to solve is rather simple. When the project was initiated, there was no PIM-Suite available which
> 
> - was for this domain of users ("power-users", "commandline users")
> - uses plain text as storage format
> - was scriptable
> - was modular
> - contained functionality to link content

I would like to challenge this bold statement for being utterly wrong.

Most prominent and probably most used example of this kind of software is Emacs [Org-mode](https://orgmode.org). The fact that you don't like ["the other editor"](https://imag-pim.org/doc/web/0.5.0/) (which is [not just an editor](http://karl-voit.at/2015/10/23/Emacs-is-not-just-an-editor/) at all) does not mean that you have to ignore the fact that there **are** solutions out there which perfectly fit to the valid requirements you describe above.

A second project that would fit to this set is [Zim](http://zim-wiki.org/) or many other instances of the whole class of [Personal Wiki](https://en.wikipedia.org/wiki/Personal_wiki)s.

Don't get me wrong: your project seems to be very cool and please try to make the best PIM system there is. However, you should be honest about your project so that people stumbling over [pages like this](https://imag-pim.org/doc/web/0.5.0/) don't get the wrong idea that there is only imag which tries to address the requirements mentioned.

This issue might seem to be nitpicking. Although for the underlying motivation, the basic idea, the situation in general you should not start on wrong statements.

**Comment by matthiasbeyer** [comment]
Hi. Thanks for reporting this. You are very right and I will address this before the 0.6.0 release!

**Comment by matthiasbeyer** [comment]
Closed as #1232 is merged now. Feel free to point out more things you would like to have clearified! Every contribution counts!

**Comment by novoid** [comment]
Slightly connected remark, since I don't want to open another issue for it: think about adding a short screencast to the README: it gives a first impression of basic features of imag.

I have positive experience for https://obsproject.com/ (videos) and https://github.com/phw/peek (animated GIFs).

**Comment by matthiasbeyer** [comment]
Definitively a good idea, though as we are not yet that feature rich I would postpone this until we have actually something to show 😄
