### ISSUE TITLE
store: EntryHeader should build a standard-header

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#127]
I guess the `EntryHeader::new()` function should not get a `table` passed but build its own one and set some default entities within.

What do you think?

This is an interface-change!

**Comment by neithernut** [comment]
It sure makes sense to have an interface which forces the creator of an entry to provide some non-optional information. The required fields should be deferrable from the specification.

**Comment by matthiasbeyer** [comment]
Ack. I will change the interface asap.
