### ISSUE TITLE
[RFC] [Store]: Entry-getter to iterate over entries of a module

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#138]
Problem:

I'm a module which allowes the user to tag entries. I want to offer an option "list all entries with tag 'X'" to the user. I have no possibility to load all entries which belong to me.

The proposed solution:

Provide a `Store::retrieve_for_module()` which allows to iterate over all entries for given module. Version foo should be considered, of course.

Such an interface would look something like this:

```rust
pub fn retrieve_for_module(&self, mod_name: &str, mod_version: &str) -> FileLockEntryIterator {
    unimplemented!()
}
```

**Comment by neithernut** [comment]
There are a few considerations to make:
 * mod_version being a raw string is probably not as ideal as it could be. Maybe we could use a special data type for that.
 * What are the exact semantics of `mod_version`? Is it the minimum version, the exact version or a range (possibly implicitly provided by omitting e.g. the minor level)? Can this be an optional parameter?
 * Of what kind should the iterator be? @matthiasbeyer proposes an iterator over `FileLockEntry`s, but this is not ideal for all cases, especially for cases where items are just read (he himself described such a use-case). Iterating over `StoreId`s would give you more flexibility, but it would also make things more complicated for the caller.

I'd like to propose having an alternative approach:
 * Have a method `pub fn retrieve_for_module(&self, mod_name: &str) -> StoreIdIterator`.
 * Provide facilities for easy filtering by available versions (which can be easily used with `Iterator::filter()`)
 * Users can easily invoke `Iterator::map()` with a closure calling `Store::retrieve()` or `retrieve::copy()`, just as they please.

----

Thinking about this: maybe the signatures of `Store::retrieve()` and `Store::retrieve_copy()` have to be adjusted to accommodate for the fact that we know version entries? I'll open an issue for this.

**Comment by matthiasbeyer** [comment]
I agree with you on the `StoreIdIterator` part. Filtering would then be done by the callee, which is completely fine.
