### ISSUE TITLE
Extend interface for entry retrieval to filter by version

### ISSUE THREAD

**Issue by neithernut** [matthiasbeyer/imag#139]
Given the fact that we know want to allow multiple versions of an entry (see #123), we have to extend the existing `Store` interface to accommodate for this:
 * [ ] `Store::retrieve()` needs a new (optional?) parameter for confining the versions allowed for the entry it returns.
 * [ ] So does `Store::retrieve_copy()`
 * [ ] A function returning all versions an entry is available in would also be nice.

**Comment by TheNeikos** [comment]
An entry will only ever be available in one version or it is invalid

**Comment by neithernut** [comment]
I didn't find anything in the documentation stating this. Maybe this piece of information is missing?

**Comment by TheNeikos** [comment]
Indeed, while I did mention it while we discussed it, I forgot to mention it while we merged the RFC. I will change that now.

**Comment by neithernut** [comment]
In this case, this issue can be closed.

**Comment by TheNeikos** [comment]
Just submitted #140
