### ISSUE TITLE
Crate documentation URL broken

### ISSUE THREAD

**Issue by thedanielgray** [matthiasbeyer/imag#1402]
In the title block at https://crates.io/crates/imag-ref:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/7434508/38823722-29ca2a82-4175-11e8-9539-d28c76193140.png">
The documentation link points to https://matthiasbeyer.github.io/imag/imag_documentation/index.html which seems to have been taken down by you. I guess that the correct link would be http://imag-pim.org/doc/.

**Comment by matthiasbeyer** [comment]
Hey, thanks for reporting this!

I will push a fix to the minor branch, which will be merged before the next release (probably this week).

Thank you very much! <3
