### ISSUE TITLE
Iterator::flatten is pending stabilization

### ISSUE THREAD

**Issue by Centril** [matthiasbeyer/imag#1497]
The function `Iterator::flatten` is pending stabilization (see https://github.com/rust-lang/rust/pull/51511).
The regression was fixed in https://github.com/matthiasbeyer/imag/pull/1491 but it hasn't been released yet so I am filing this issue to notify y'all.

Thanks :)

**Comment by matthiasbeyer** [comment]
Thank you for your issue.

As the issue template told, I am currently on a sabatical until early 2019 and do not have the resources to do a new release, I am sorry.
I will, of course, look into this as soon as possible (which might be early 2019).

Either way, thank you for your contribution.

**Comment by matthiasbeyer** [comment]
Because we are now [moving off of github](https://github.com/matthiasbeyer/imag/pull/1505) I'm closing this PR/Issue now. The reasons why we do this was described in a [blogpost](https://imag-pim.org/blog/2018/06/10/off-of-github/). Feel free to resubmit this PR/Issue via the mailinglist.
