### ISSUE TITLE
Redefine how a module gets all its entries.

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#168]
This is from a face-to-face discussion with @TheNeikos .

---

So the basic problem is, that a module may want to get _all_ entries which are available in the store, which are written by the module itself. We have `libimagstore::store::Store::retrieve_for_module()` for this, though this does not fit our needs anymore. We need to redefine this in a sane way.

---

Usecase: `imag bookmark list --all`

**Comment by matthiasbeyer** [comment]
@TheNeikos ping.

**Comment by neithernut** [comment]
Could you elaborate on why `libimagstore::store::Store::retrieve_for_module()` doesn't meet the requirements?

**Comment by matthiasbeyer** [comment]
The discussion with @TheNeikos was several days ago, so I'm not sure anymore. As far as I can remember, @TheNeikos introduced the `module_entry_path_mod!()` macro which generates code for Entry-Path creation and the `retrieve_for_module()` interface doesn't match this concept somehow.

I guess @TheNeikos can explain a bit better.

**Comment by TheNeikos** [comment]
Yeah, basically the thing is that you shouldn't be able to load entries from another module, but rather load it through their public interfaces.

**Comment by neithernut** [comment]
Now that kinda makes sense. But doesn't this also affect other methods, e.g. `retrieve()`, as you are able to get an entry via its id regardless of what module it belongs too?
Wouldn't a policy like "libstore (or some group of methods from it) is never used directly" make more sense?
Also: I already pointed out in other places some use-cases where the "module identity" of an entry does actually _not_ represent some library/module but some concept (e.g. "music"). In such situations, it is absolutely legitimate to use one string from different pieces of software or from plug-ins, albeit one would still want enforce some constrains, e.g. regarding the metadata stored for an entry.

----

One actual solution which pops into my mind is having a trait `module` which is, as the name suggests, implemented by each module. It would provide a name or a string for identification. If some action would require providing a (valid) module, one would simply pass this object. The method would then extract said string and use it for filtering.
If those handlers are installed, e.g. into a hash-map or multi-map, one could also use them for deferring/delegating some tasks to specific modules. This way, a module could enforce the validity of some metadata. If we allow some class of handlers to be applied on _all_ entries, regardless of their "module identity", we could also use this to implement stuff like #194.

**Comment by TheNeikos** [comment]
that is what I tried to show in the macro I wrote

**Comment by matthiasbeyer** [comment]
Still no decision here?

**Comment by matthiasbeyer** [comment]
Still no decision here?

**Comment by neithernut** [comment]
The hook-infrastructure might have made this issue obsolete.

**Comment by matthiasbeyer** [comment]
Nope it doesn't. I have implemented a store function to do this (simply pass the module name and it globs for storeids), though I'm on mobile and won't be able to push until tomorrow.

**Comment by neithernut** [comment]
Well, what I meant was that `store::retrieve_for_module()` is sufficient, once it is implemented.

**Comment by matthiasbeyer** [comment]
That's the function I implemented, indeed. :+1:
