### ISSUE TITLE
[Feature Request] Store::move()

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#169]
We could use a `Store::move()` functionality, which moves an Entry from one place to another, for renaming entries.

**Comment by matthiasbeyer** [comment]
Interface would look like this:

```rs
pub fn move(&self, id: StoreId, new_id: StoreId) -> Result<()> {
    unimplemented!()
}
```

@TheNeikos , @neithernut

**Comment by neithernut** [comment]
Sounds reasonable.

**Comment by TheNeikos** [comment]
Yup

**Comment by matthiasbeyer** [comment]
@TheNeikos wanna implement such a thing?
