### ISSUE TITLE
[question/rfc] Library for tags?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#172]
Should we create a library for _tagging_ single entries in the store? If yes, do we need a specification how tags are stored, similar to how links are stored?

@TheNeikos, @neithernut

**Comment by neithernut** [comment]
Tagging would be nice. The most forward way to implement this is to store tags as a list of strings in each entry IMO.

**Comment by matthiasbeyer** [comment]
Exactly. We still have to define where. I guess the `imag` section should get a key `tags`.
