### ISSUE TITLE
Store does not `flock()` yet

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#175]
AFAICS, the store does not `flock()` an entry, yet. We should implement this.

**Comment by TheNeikos** [comment]
:+1:

**Comment by matthiasbeyer** [comment]
@TheNeikos wanna do this now?

**Comment by matthiasbeyer** [comment]
This will be put on hold now, as this is a thing which can be implemented with the hook system, as soon the hook system is up and running ... ( #200 ).
