### ISSUE TITLE
Add test-coverage statistics tool

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#182]
@TheNeikos has something for us, right?

**Comment by TheNeikos** [comment]
:? In rust? I don't know

**Comment by matthiasbeyer** [comment]
I guess https://users.rust-lang.org/t/tutorial-how-to-collect-test-coverages-for-rust-project/650 helps us, though I don't think we should do this on travis, as we would need to build our own `kcov` binary. And we really don't want to do this on travis, right?

**Comment by TheNeikos** [comment]
Well, it would make it each build longer!

**Comment by TheNeikos** [comment]
I also don't think that coverage is something we need.

**Comment by matthiasbeyer** [comment]
Not yet, at least. I will put this on hold and reopen later and then close this issue.

**Comment by matthiasbeyer** [comment]
kkkk
