### ISSUE TITLE
[RFC] [store]: hook layer

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#199]
I think we should add a Hook layer to the store, which then can be used to execute hooks before and after {CRUD} actions. These Hooks should be able to abort store actions. These Hook actions should even be able to provide dependency-hook actions, so we can seperate Hooks and re-use them in a niceish way.

In the store we would need:

* A way to `register()` hooks with the store
  * for create
  * for read
  * for update
  * for delete
* One error type for wrapping Hook errors

As hook interface:

* A trait which gives us
  * an `explanation()` method which explains the hook to the user
  * an `execute()` for the hook
  * a `dependency_hooks()` which returns a `Vec<Hook>` which must be succeed before `Self`
* Hook error types
* An `enum` for identifying when the hook should be executed(1)

---

(1) I'm not sure whether an enum with `PreRead`, `PostRead` etc would be better or custom traits for each hook

---

With a hook system we could implement:

* git (including switching it on and off via configuration) or other VCS
* Link-consistency checkers
* Markup checkers (whether the user entered correct markup, would reduce noise in the binaries)
* even more great things...

and because some traits should be deeply integrated I would also opt for a standard-set of hooks (which are enabled by default, but could be disabled) which are `registered()` with the store upon creation of the `Store` object.

---

I propose to intergrate this with the store itself, for simplicity of the codebase as well as bundling this feature with the store. This way, the hooks are not "enable if you want" but preconfigured hooks are simple to implement and all this stuff is even backwards compatible with the current store interface!

**Comment by matthiasbeyer** [comment]
If we do this and store the registered hooks in the store itself, we must be able to alter the `Store` object, thus `mut`. The `Store` object is stored in the `Runtime` object, which is immutable.

So we would need a way to alter the `Store` objects internals without making the `Store` itself mutable.

**Comment by neithernut** [comment]
Sounds great. I'd like to sleep over it though, before commenting on it in detail.

**Comment by matthiasbeyer** [comment]
#200 is just a proposal to the upper idea. It is implemented without the `enum` but with traits for each kind of hook, which I find a bit better, but which also introduces a bit overhead in the `Store` object implementation.

**Comment by neithernut** [comment]
Using traits and having the hooks/functions be methods required by the traits would have a number of benefits.

**Comment by matthiasbeyer** [comment]
And a number of drawbacks, as the implementation is rather complicated (see #200).

**Comment by neithernut** [comment]
I see it now.

**Comment by matthiasbeyer** [comment]
I'm currently thinking about the following issue:

As @neithernut suggested, some hooks may want to change the content of the objects they hook up with. Some may not want this. This gives us the possibility to parallelize _some_ of the hooks.

Overall: If there is at least one hook which wants the data mutable, we cannot execute hooks in parallel. If there is none, we can execute all hooks in parallel.

This also is influenced by sorting. If the first or last hook wants to mutate data, we can execute all others in parallel.

I'm not sure how one would implement such a scheme. What I'm thinking about:

A Hook returns a `enum HookAccessorStrategy<A, B>{ MutableAccessor(A), NonmutableAccessor(B) }` and we dispatch via this.

@TheNeikos Thoughts? This would, of course, make the implementation even more verbose.
