### ISSUE TITLE
Simplify travis testing

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#202]
As we build all crates in the repo, we could use https://github.com/jonas-schievink/cargo-local-pkgs

**Comment by TheNeikos** [comment]
Sounds like a useful thing to have!

**Comment by matthiasbeyer** [comment]
Waiting for the workspaces feature in rust/cargo.

**Comment by matthiasbeyer** [comment]
I guess our `Makefile` is appropriate enough.
