### ISSUE TITLE
[imag-store]: Rewrite UI with clap `ArgGroup` features

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#208]
( start after #207 is merged )

`clap` provides features to group arguments. This way 

* "one of these" restriction can be applied to 
  * https://github.com/matthiasbeyer/imag/blob/master/imag-store/src/ui.rs#L8-L18
  * https://github.com/matthiasbeyer/imag/blob/master/imag-store/src/ui.rs#L19-L42
  * https://github.com/matthiasbeyer/imag/blob/master/imag-store/src/ui.rs#L54-L61
  * https://github.com/matthiasbeyer/imag/blob/master/imag-store/src/ui.rs#L62-L69
  * https://github.com/matthiasbeyer/imag/blob/master/imag-store/src/ui.rs#L73-L83

**Comment by uomoinverde** [comment]
Should you close this?

**Comment by matthiasbeyer** [comment]
I guess this can be closed.
