### ISSUE TITLE
Change license to GPLv2

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#236]
I'm recently thinking about relicensing this under terms of GPLv2.

@neithernut and @TheNeikos you contributed code to this project and this would need your approval, though I'd like to hear whether you have objections...

**Comment by neithernut** [comment]
Licensing `imag` under GPLv2 would shut out a lot of programs from using any of the libraries for direct access to the store. This would suck.

**Comment by matthiasbeyer** [comment]
It would not shut them out if they are GPLish or GPL compatible (and that's what I have in mind, actually).

**Comment by neithernut** [comment]
So you want to force users of the libraries to either license their software under GPL (or compatible licenses, which are few) or re-implement imag, if they want to use an imag-store?

**Comment by matthiasbeyer** [comment]
Yes. What I really want to do is to block out proprietary code. The LGPL allows proprietary code to link to the code. I don't care about MIT/Apache2/BSD licensed code which links to this, though I want to remove the possibility to link to this codebase from proprietary code.

**Comment by neithernut** [comment]
You still gain nothing but contribute to the fragmentation of the open-source community:
 * There is dispute of whether software disclosed under a permissive license can legally link to GPL libraries. So you effectively shut out any non-GPL software.
 * If LGPL libraries are used in proprietary products, the library either has to be installed on the target already or, if the library is shipped with the product, the use of the library must be properly declared and the source-code must be made available. So what's the problem?

**Comment by matthiasbeyer** [comment]
The Problem I'm thinking about is that there _can be_ proprietary products based on this.

What I want is something like a GPLv2.1 with an explicite exception for MIT/Apache2/BSD-Licensed software and probably some other licenses. Though I doubt something like this exists.

**Comment by TheNeikos** [comment]
I agree with @neithernut, there is no reason to close it down that far.

Remember, the LGPL basically allows you to link to it without having to reveal your source when distributing it. 

Why would you care about closed source code around it? It does not make the situation worse for anyone but potential users.

**Comment by matthiasbeyer** [comment]
Okay.
