### ISSUE TITLE
Filter DSL

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#245]
I want to introduce a Filter "DSL" which would be implemented within `libimagentryfilter` to provide a `--filter <filter_string>` commandline argument which can be integrated into the commandline.

This DSL must provide:
- Access to all builtin filters
- Access to all non-builtin filters which are added from a library via the `Filter` trait

The interface from `libimagentryfilter` must provide:
- A builder for the commandline argument (trivial)
- A compiler function which translates `&str -> Result<Box<Filter>, FilterCompilerError>` (non-trivial)

---
# DSL

The DSL itself would be rather simple:
- Each filter has a name, this name can be called with `name()`
- inside the parentheses of a filter call, there can be arguments to modify the filter
  - For example: `header_field_eq(header.path.field, String(foo))` would return a `FieldEq` filter which would filter for the header field at `header.path.field` to be equal to the string `"foo"`.

Syntax elements such as `and` (or `&&`), `or` (or `||`), `not` (or `!`), `xor` (or `^`) should be provided.

So a more complex filter source would look like this:

```
imag module list --filter "header_field_eq(foo.bar, String(1)) && !header_field_eq(foo.baz, String(2))"
```
## Dreams...

I think the upper DSL would be nice, though here goes what I'd love to have:

```
imag module list --filter "$H.foo.bar == String(1) && $C.grep('Something')"
```

where `$H` is a variable for the header and `$C` is for the content. `$H.foo.bar` translates therefor to "The header field at 'foo.bar'" and `$C.grep()` translates to "The content should be grep'd".

If someone wants to play with parsing and so on, go ahead! `nom` is a (afaik) good crate for parsing things.
# Importance of this

This is not that crititcal by now, but will become rather important as soon as we start to implement bigger modules. The filter infrastructure which is already there should become a consistent interface all modules can use and this is the very heart of it. With this, we can provide _one_ filtering interface over _all_ modules, which I consider rather important to our main goals.

**Comment by matthiasbeyer** [comment]
@asuivelentine had some interesting ideas how this functionality can be implemented.

The problem is, that the `libimagentryfilter` can only offer some _very_ basic filter operations (syntax wise). For example "does the header at foo.bar contain a 'foo' string" or something like this. This is not a high-level "language".

What @asuivelentine proposed was an approach which could be described as "partial interpreting". Lets assume we have the following stack of modules:

* ModuleA -> FilterLibrary

The `ModuleA` would generate an `AST` from the filter string input, transform every module-specific syntax nodes into `FilterLibrary` syntax nodes and then pass it to the filter library which generates the filters.

If we have a stack like this:

* ModuleA -> ModuleB -> FilterLibrary

The AST would be transformed by `ModuleA`, passed to `ModuleB` which also transforms it and pass it to the `FilterLibrary` which builds the `Filter` objects.

The problem now is, that a module may depend on more than just one other module:

* ModuleA -> ModuleB -> FilterLibrary
* ModuleA -> ModuleC -> FilterLibrary

And now things get ugly. The module `ModuleA` would need to transform the AST, pass it to `ModuleB` so that module can transform it, pass it then to `ModuleC` which also transforms it and _then_ pass it to the `FilterLibrary`.
So a module would need to export a functionality to transform the AST _without_ passing it to its dependency modules. But what if `ModuleC` depends on `ModuleB` as well? The AST would be compiled twice by `ModuleB`. This is not a big problem, but it _could_ become ugly at some point.

---

So what do we have?

* The filter library
  * must include an tokenizer which does not yet know about all of the tokens
  * Each token may be transformed to another sub-AST
* A module 
  * must be able to transform an AST
  * must be allowed to pass the AST to its dependencies to transform the AST
  
I guess that's it on a fairly high level.

**Comment by neithernut** [comment]
I do not really understand how this is a problem.

When exposing a extensible parser, it's pretty normal that you have some facility for registration of extensions (filters in this case). The parser would simply build the AST from the syntax and resolve the names or symbols it encounters, which may or may not involve looking up stuff in the registry. I see absolutely no reason to pass around the AST to other modules for mere resolution of names or symbols.

**Comment by matthiasbeyer** [comment]
Doing it via a registry would be another possibility, yes.

**Comment by matthiasbeyer** [comment]
The idea with the registry bugs me. I guess this is a very good idea. We could use the [combine](https://marwes.github.io/combine/combine/index.html) crate to parse the tokens and the core syntax (such as "function calls" or operators) and then use a registry to resolve the symbols to actual functions.

**Comment by matthiasbeyer** [comment]
An interface for

- [ ] Lua (via https://github.com/tomaka/hlua)
- [ ] LISP (via https://github.com/murarth/ketos)

could be added as well.

**Comment by matthiasbeyer** [comment]
I just found [rhai](https://github.com/jonathandturner/rhai) which seems to be a _perfect_ fit for our needs here.

It seems to be easily embeddable and provides everything we need. Awesome!

**Comment by Marwes** [comment]
Saw this mentioned in TWIR and thought I could ask if you have considered [gluon](https://github.com/Marwes/gluon)? If you have considered it and decided it did not fit that would also be useful knowledge since it may help identify weaknesses in it.

**Comment by matthiasbeyer** [comment]
@Marwes Hi! Thanks for mentioning gluon! It looks really nice! My use-case is, that a user can script directly on the commandline:

```bash
$ imag foo --filter="entry.has_header('bar')"
```

or something like that - for this usecase a scripting (non-typed) language is better IMHO. I keep gluon in mind - maybe it can be useful elsewhere in imag! Thanks for mentioning it!

**Comment by Marwes** [comment]
Thanks for responding! Figured that would be the issue :). Dynamism is definitely important for this use-case and really for most uses of an embedded language. One sort of goal I have for gluon is that it should be possible to read it without realizing that it is a static language. And when writing it it should have a dynamic enough feel that the typechecker mostly lets you do dynamic looking things but is still able to step in when you actually make an error. Its not there yet but with a few additions such as [row polymophism](https://github.com/Marwes/gluon/pull/132)) it might get there.

**Comment by matthiasbeyer** [comment]
Because we are now [moving off of github](https://github.com/matthiasbeyer/imag/pull/1505) I'm closing this PR/Issue now. The reasons why we do this was described in a [blogpost](https://imag-pim.org/blog/2018/06/10/off-of-github/). Feel free to resubmit this PR/Issue via the mailinglist.
