### ISSUE TITLE
Store has PreRead aspects, but they are never used

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#264]
They should be removed.

-> https://github.com/matthiasbeyer/imag/blob/master/libimagstore/src/store.rs#L226-L227

These aspects are created but never used actually, because the actual "read" aspects are the "retrieve" aspects.

@asuivelentine wanna doing this?

**Comment by asuivelentine** [comment]
sure -> done

**Comment by matthiasbeyer** [comment]
@asuivelentine You know you don't always have to send patches per mail and it is perfectly fine to send patches via PR on github? :-) Anyways, thanks for the patch!
