### ISSUE TITLE
Store should automatically fallback to latest version of entry

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#294]
If we load an entry `/foo/bar`, we do not pass the version of the entry which should be loaded.

The store should fallback to the last version instead of failing.

This is mainly useful for the user interface, of course.

**Comment by neithernut** [comment]
This issue's headline does not match the description: do you mean the _latest_ version or the _oldest_?

**Comment by matthiasbeyer** [comment]
Wah, yes. The latest.

**Comment by matthiasbeyer** [comment]
This becomes really annoying, we should takle this soon. I added the `importance/high` label therefor.

**Comment by mario-kr** [comment]
Question: With #667 , wouldnt the version part be removed, rendering this issue obsolete?

**Comment by matthiasbeyer** [comment]
@mario-kr yes.

**Comment by neithernut** [comment]
Well, than you should probably clode this issue once #667 is merged.

**Comment by matthiasbeyer** [comment]
Obsolete now.
