### ISSUE TITLE
Remove warnings from libimagutil

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#314]
Compiling libimagutil spits out some warnings.

These should be fixed and the appropriate `deny!()` flags should be set.

For possible contributors: See #283 for example.

**Comment by uomoinverde** [comment]
Should you maybe close this issue? Taking a look at libimagutil, it seems to have been already fixed.

**Comment by matthiasbeyer** [comment]
Ah, yes! Thanks for mentioning!
