### ISSUE TITLE
Change travis setup to use docker

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#340]
@TheNeikos Can you please do this for us?

Would be amazing of you. This way we would be able to run the builds on at least kindof-latest-version images.

Something like Debian 8 and Ubuntu (latest LTS) would be awesome!

Optionally we can do this together in a pair-programming session, but I know too little about docker to do this on my own...

**Comment by TheNeikos** [comment]
I am not sure what you mean

**Comment by matthiasbeyer** [comment]
Travis has the possibility to run tests in a customized docker container. The repository can contain such a docker container.

What I want from you is to change the travis setup so our tests run in a custom docker container with the dependencies installed.

**Comment by TheNeikos** [comment]
I see, but travis doesn't allow arbitrary docker files to be used. (Unless I missed an announcement)

**Comment by matthiasbeyer** [comment]
AFAICS it allows them: https://docs.travis-ci.com/user/docker/

**Comment by TheNeikos** [comment]
Ya, that is to run docker in the build, but not choose your docker image

**Comment by matthiasbeyer** [comment]
:cry:

**Comment by TheNeikos** [comment]
:disappointed: \
