### ISSUE TITLE
Add labels' guidelines to CONTRIBUTING.

### ISSUE THREAD

**Issue by uomoinverde** [matthiasbeyer/imag#409]
As in projects like [Atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#issue-and-pull-request-labels) or [Rust](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#issue-triage), ``imag`` would surely benefit from a well-established labelling system, laid out in the CONTRIBUTING file.

## To-Do

  1. Specify labels categories: complexity, kind, meta, part, bug, ...
  2. Specify label colors :art:
  3. Specify subcategories: for `complexity`, it would be easy/medium/hard/insane.

**Comment by matthiasbeyer** [comment]
We already have labels, but I agree with you that we should add explanations for these in the `CONTRIBUTING.md` file.

**Comment by uomoinverde** [comment]
I think this can be closed. :+1:
