### ISSUE TITLE
Simplify Error generation with new error setup

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#434]
We had nice changes in the merge for `libimagerror` #410.

We should slowly change the codebase to use the new error setup and replace:

```rust
foo.map_err(|e| SomeError::new(SomeErrorKind::FooError, Some(Box::new(e))))
```

with

```rust
foo.map_err(Box::new)
    .map_err(|e| SomeErrorKind::FooError.into_error_with_cause(e))
```

and

```rust
return SomeError::new(SomeErrorKind::FooError, None);
```

into 

```rust
return SomeErrorKind::FooError.into();
```

Which is way more readable.

---

This is a long-standing issue until the whole codebase is cleaned up.

**Comment by matthiasbeyer** [comment]
@TheNeikos Question:

Why do we have to write `.map_err(|e| ...into_error_with_cause(e))` and cannot write `.map_err(...into_error_with_cause)` ? I tried and it failed...

I mean, we can write `foo.map(String::from)` instead of `foo.map(|s| String::from(s))` - why not the above?

**Comment by matthiasbeyer** [comment]
Started in #441 #442 #443 and #444

**Comment by TheNeikos** [comment]
> @TheNeikos Question:
> 
> Why do we have to write .map_err(|e| ...into_error_with_cause(e)) and cannot write .map_err(...into_error_with_cause) ? I tried and it failed...
> 
> I mean, we can write foo.map(String::from) instead of foo.map(|s| String::from(s)) - why not the above?

You can do this: `.map_err(<Object as Trait>::into_error_with_cause)` or something similar, but not a single dot notation
