### ISSUE TITLE
Add imag-binary to makefile

### ISSUE THREAD

**Issue by mario-kr** [matthiasbeyer/imag#478]
the bin-directory isnt included in the Makefile yet.
Also, running imag properly still requires the environment variable `IMAG_IS_THE_SHIT`. Is it possible to let imag know where its binaries are during compiletime instead of runtime?

**Comment by matthiasbeyer** [comment]
The idea on compiletime... You could add the `/out/` into `$PATH`.

**Comment by mario-kr** [comment]
If i add `.../out` to `$PATH`, I can call those binaries, but what about `./bin/target/debug/imag`? My suggestion was to hardcode the path, in which `bin/.../imag` searches the binaries, by giving the information at compiletime (through cargo? or environment?). 
And i just noticed that a release target might be useful for Users (non-developers).

**Comment by matthiasbeyer** [comment]
@mario-kr the binaries from `target/debug/imag` get copied to `out`. This is not (yet) true for `bin/`.

I do not think about releases in any way, `imag` is a moving target and not expected to be used in production by now.

**Comment by lucc** [comment]
Could you update the Readme to give the new instructions for running the program?

**Comment by mario-kr** [comment]
Hello,
I'm currently working a bit on the Makefile, see #504 . I'm kinda busy with other stuff right now, so it might take some time. I'll put an "update Readme" on my todo-list.

**Comment by matthiasbeyer** [comment]
@lucc thanks for mentioning it!

@mario-kr sounds good, I'm rather busy right now as well, but I hope to get some neat things done this week (I try to focus on the user documentation a bit).

**Comment by mario-kr** [comment]
Closed by:
#646 
#649 
#665 
#670
