### ISSUE TITLE
IMDB support

### ISSUE THREAD

**Issue by jarun** [matthiasbeyer/imag#488]
First of all, this is a great tool, gives a feel of a fully-blown workspace in the cmdline. Thank you!

I'm not sure if this is out of scope or not. But it would be great if you can support fetching movie information from IMDB.

**Comment by matthiasbeyer** [comment]
Hi!

Awesome that you opened an issue on this, thanks a lot!

That's definitively in scope of this project, though it may take some time until we get there. I will include this in the `movie` module.

**Comment by jarun** [comment]
:+1:

**Comment by matthiasbeyer** [comment]
I will mark this as reopen-later and close this, I hope this is okay with you, @jarun!

**Comment by jarun** [comment]
:+1:

**Comment by jarun** [comment]
Leaving a quick note: if possible, please support GCStar database import (it's a plaintext) when you add IMDB support.

**Comment by matthiasbeyer** [comment]
TIL about GCStar - looks like a cool piece of software and even has a CLI (though a limited one). I will consider it (though as always: We are _slow_ here, as this is a monster project and also a private hobby project, so don't be disappointed if things move _really_ slowly!)

**Comment by jarun** [comment]
It was a charm! Till IMDB import broke over the past 2 years. It's as good as [unmaintained](http://forums.gcstar.org/viewforum.php?id=2) now.
