### ISSUE TITLE
imag binary --help doesnt show commands

### ISSUE THREAD

**Issue by mario-kr** [matthiasbeyer/imag#491]
Hello,
after calling cargo install for every binary and imag/bin, something like
```sh
imag view --help
```
works as expected, however
```sh
imag --help
```
doesnt actually show any comments.
This might as well be a local problem, so this Issue can be closed anytime.
greetings

**Comment by matthiasbeyer** [comment]
Yep, I guess I can confirm that... not sure though, will have to investigate.

Thanks for reporting.

**Comment by mario-kr** [comment]
I looked over it a bit, and it might be more secure to use Path::file_name at https://github.com/matthiasbeyer/imag/blob/master/bin/src/main.rs#L71 , so you dont check with the whole path. Currently you check if the path starts with `$PATH_ELEM/imag-*`, with this you can check only for `imag-*`
