### ISSUE TITLE
Make commandline consistent

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#493]
This might be a rather long-running issue.

We have many commandline arguments which basically are the same, but which are named inconsistenly over several CLI frontends.

We should make them all the same, possibly by providing a crate for some commandline arguments which appear rather often (such as `--id` or `-i`).

---

This is really easy to do, actually. Questions are welcome, anyway! :smile: 

---

We _could_ use https://github.com/kbknapp/clap-rs/blob/master/examples/20_aliases.rs#L9 (clap alias feature) to make it backwards compatible, though I wouldn't mind if this would break the existing CLI interface, as we are not released yet... so who cares?

**Comment by mckeankylej** [comment]
If it's okay with you I would like this to be my first project on this repo as it looks easy enough. Keep in mind I know 0 rust so I will be learning as I go, if you want a high quality pr for this I suggest telling me to look at other issues ;) also I will most likely have silly rust beginner questions, if you're okay with it would you please pm me your number so I could text you my questions.

**Comment by matthiasbeyer** [comment]
I cannot PM you as github has no feature for this, but feel free to write me an email (my mailaddr is on my github account page). This issue is indeed easy, but I guess not so if you have literally zero experience with rust, ... so I would consider another one. Maybe #507 or #476 or #463 .

**Comment by matthiasbeyer** [comment]
Partly WIP In #596

**Comment by mario-kr** [comment]
@matthiasbeyer Seems like there's no need to open a new issue explicitely for `imag-link`, but instead write it down here:
`imag link internal` offers subcommands to add/remove a link;
`imag link external` offers options instead.
