### ISSUE TITLE
Optimize: `fold(Ok(()), ...`

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#499]
@TheNeikos I ping you because we talked yesterday.

One thing that could be optimized is the use of `Iterator::fold` to fold an `Ok(())` and to break iterating on error.

We have 8 occurrences in the code where I do

```rust
foo.iter().fold(Ok(()), |acc, elem| acc.and_then(|_| elem.do_something()))
```

We could optimize this by providing a `Iterator::fold_ok` which hides the passing ok `Ok(())` and the use of `and_then()` and simply applies the closure.

This could be done in a new helper crate `libimagiter` or in `libimagutil` (I guess the latter is sufficient).

**Comment by bjorn3** [comment]
Could you use `.map(_).collect::<Result<Vec<T>, E>>()`?

**Comment by matthiasbeyer** [comment]
No, as `fold()` calulates _one_ result rather than a list of results (as in value, not as in `Result`).

Have a look at [the documentation for fold](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.fold), it is not an advanced `map()`! The result is of type `Result<T, E>` rather than `Result<Vec<T>, E>` as you described it.

**Comment by bjorn3** [comment]
Oops

**Comment by jsirois** [comment]
Can this be closed or is there more work to do?

**Comment by matthiasbeyer** [comment]
Oh, it wasn't closed by the merge ... I'm sorry. Yes it can be closed! Thanks for mentioning!
