### ISSUE TITLE
UI Wrapper Framework around clap?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#505]
We have a lot of inconsistency in the UI of the binary crates. Maybe we could create a wrapper framework around clap which helps with creating the UI? At least for the CRUD actions most CLI interfaces offer?

Would name it libimagcli. Maybe this could also go into libimagutil, would make sense IMHO.

**Comment by matthiasbeyer** [comment]
A fix for this would close #493 as well.

**Comment by asuivelentine** [comment]
I'll try this

**Comment by matthiasbeyer** [comment]
Considered abandoned.
