### ISSUE TITLE
Make `imag` forward `--debug` and `--verbose` and maybe others

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#506]
Today we call `imag foo --debug`, but we also should be able to call `imag --debug foo`.

So the `imag` binary should catch the `--debug` parameter and call `imag-foo --debug` in the upper case.

This would be a nice embelishment, IMHO.

**Comment by Geemili** [comment]
I added in forwarding for the `--debug` flag, and also fixed an issue were the root command wouldn't acknowledge flags. #564

**Comment by matthiasbeyer** [comment]
Closed with merge of #564 

`--debug` gets forwarded now, `--verbose` not yet. But as we might switch to clap (#566) I guess this can be closed anyways.
