### ISSUE TITLE
Deny warnings in libimagentrylink

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#507]
`libimagentrylink` does not seem to deny warnings.

We should enable this feature.

**Comment by impo** [comment]
I'd like to work on this issue but I'm not sure what denying warnings is. Is it just what's described in the link below?
[https://users.rust-lang.org/t/how-to-fail-a-build-with-warnings/2687](https://users.rust-lang.org/t/how-to-fail-a-build-with-warnings/2687)

**Comment by matthiasbeyer** [comment]
@impo yes, basically.

Have a look at this: https://github.com/matthiasbeyer/imag/blob/master/libimagstore/src/lib.rs#L1-L13

This denies all warnings we want to deny. Just paste the very same snippet in the `lib.rs` file of `libimagentrylink` and try to `cargo build` (or `cargo check`, if you have it installed) it - then you can start fixing warnings!

:+1: nice you want to do this! Thanks a lot! :smile:

**Comment by impo** [comment]
...huh. It looks like those lints have been in place in `libimagentrylink` for a few months now. When I run `cargo build`, I don't get any errors or warnings off of that crate.

See: [this commit](https://github.com/matthiasbeyer/imag/blame/master/libimagentrylink/src/lib.rs#L1-L13)

**Comment by matthiasbeyer** [comment]
... hm. Maybe I confused two crates. Feel free to look at all other `libimag*` crates to check whether these `deny(...)` snippets are in place! :smile:
