### ISSUE TITLE
We use `unwrap()` too extensively

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#576]
In some cases it might be okay to use `Option::unwrap()` and `Result::unwarp()` - but I guess we can reduce the number of `unwrap()` calls anyways.

At the moment we have:

``` bash
ag unwrap -c | cut -d: -f 2 | sed 's,$, + ,' | tr -d '\n' | sed 's,$,0\n,' | bc
```

-> `304` unwraps in the codebase.

That is too much.

---

This issue is a long-standing one, until I'm satisfied with the number of `unwrap()`s again. PRs should be files per-crate for removing `unwrap()` calls!

**Comment by matthiasbeyer** [comment]
At least there should be comments why a call to `unwrap()` might not be problematic in some cases (for example if `clap` enforces the presence of some argument).

**Comment by asuivelentine** [comment]
libimagcounter -> done

**Comment by matthiasbeyer** [comment]
279 `unwrap`s as of eac536efa026b18eb6b94bda102994c5d1b6c5a7

**Comment by matthiasbeyer** [comment]
388 `unwrap`s as of ef07c2cba946d930e72bd5576b738987e09c2593

**Comment by matthiasbeyer** [comment]
452 as of b6917fc582303ed1be04390e9543d37170e626d5

**Comment by matthiasbeyer** [comment]
594 as of 4b906f27b1e11f2fec64b06dae5f4a258976da68

**Comment by matthiasbeyer** [comment]
I will close this issue now, as we cannot say for sure that these numbers are relevant. At least in tests, unwrapping is no harm... so we cannot trust these numbers, IMO.
