### ISSUE TITLE
[module]: Todo

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#6]

**Comment by matthiasbeyer** [comment]
We need a taskwarrior interfacing library first, but then this could be implemented.

I think of the following: This offers a subcommand `import-from-tw-hook` which can be used from taskwarrior hooks to import data.

All this module does (library):

* Inserting UUIDs from taskwarrior tasks in a entry in the store (one UUID == one entry)

And the binary:

* simply calls taskwarrior (like `alias 'imag-task'='task')

This way we can link to tasks from taskwarrior but do not duplicate work.

---

Additionally, but not for the first implementation:

* We could add a `Task` type which interfaces to taskwarrior tasks. So the user of the library can "load" tasks and tag them, add notes to it and the like, and in the background, taskwarrior gets called to modify the task

**Comment by mario-kr** [comment]
@matthiasbeyer My project group is likely to implement this feature. I think we're going to start off with the first implementation, as you explained it, and then see how far we'll get with implementing a Task type. Would that be alright?

**Comment by matthiasbeyer** [comment]
@mario-kr Hi! Would be awesome! Have a look at this: https://github.com/matthiasbeyer/task-hookrs

This is a library you can use to implement the Hook.

Here goes a quick walkthrough what has to be done:

---

1. initialize a library `libimagtask`, which
  1. Exports a `libimagtask::task::Task` type which is a wrapper arround `libimagstore::store::FileLockEntry`, this Task type has to implement
    1. `Deref<FileLockEntry>`
    1. `From<task_hookrs::task::Task>` or some custom trait for converting (as you need the Store object to generate a `FileLockEntry` for inside the `libimagtask::task::Task` type
    1. `Debug` (you can derive it most certainly)
  1. Exports functionality to load a `JSON` and generate a `task_hookrs::task::Task` from it
  1. Exports functionality to get all tasks from the store
  1. Exports functionality to get a task by UUID from the store
1.  initialize a binary `imag-task`, which
  1. offers a subcommand which can be used to write a taskwarrior hook
  1. offers subcommands to query imag for tasks

More functionality would include that you can talk to taskwarrior itself via `libimagtask`.

On the storage:

* Tasks should go into `/todo/taskwarrior/<UUID>`, where `UUID` is the UUID imported from taskwarrior
* The `FileLockEntry` header part _must_ contain the UUID at `todo.taskwarrior.uuid` and could also contain more cached information there, but I don't know whether this is neccessarry, actually.

---

Feel free to ask questions about how to implement things in here.

**Comment by matthiasbeyer** [comment]
WIP with #383

**Comment by matthiasbeyer** [comment]
#383 was merged. Closing this now.
