### ISSUE TITLE
Do we still need the version part of the storeid?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#602]
@TheNeikos I want to start a discussion whether we actually need the `~0.2.0` part of the storeids anymore.

It was introduced to be forwards-backwards compatible, but I'm pretty sure it can actually be dropped. What do you think? Maybe I'm overlooking something serious here?

**Comment by TheNeikos** [comment]
It could be dropped, however this will mean that libraries have to be careful about compatibility.

**Comment by matthiasbeyer** [comment]
That's why I'm asking. We do not have any code that deals with older versions by now. We do not have any code that deals with versions _at all_ in the libraries.

So beeing forwards/backwards-compatible would be task of the libraries then... 

---

Another question is: Does the store actually try to find old versions? If I request `foo~0.5.0` and it isn't there - does it look for older versions and does it return them? I'm pretty sure it doesn't!
