### ISSUE TITLE
Improve Makefile

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#618]
At the moment, we simply `cargo build` all the things and copy them to `./out`. A better way would be to let the `out/imag-foo` binary depend on the `imag-foo/target/debug/imag-foo` binary and define the job for this one by calling `cargo build`.

This way we wouldn't rebuild the world each time when we build all the things but only one binary changed, right?

**Comment by mario-kr** [comment]
put it on my todo-list for #504

**Comment by mario-kr** [comment]
Do we actually need the `./out/` directory? basically, developers can run what they're working on with `cargo run`, and for all of imag, they could `make install`, and just use imag in their shell like any other program (on the assumptions they have `$CARGO_HOME/bin` in their path)

**Comment by matthiasbeyer** [comment]
I'd like to keep it, as not all developers (example: me) do want to install imag into their `$CARGO_HOME/bin`. I use the `out` directory for testing!

**Comment by mario-kr** [comment]
But what can you test there you can't in the project you're working with `cargo run`, or even with `./target/debug/imag-...`, which is the exact same binary as in `out`

**Comment by matthiasbeyer** [comment]
I can do:

```bash
export PATH="$PATH:$(pwd)"
imag foo --bar --baz
```
and use the `imag` binary itself in a rather convenient way compared to use the `./target/debug` approach, as I do not have to put all `target` directories into my `$PATH`.

**Comment by mario-kr** [comment]
Ok, I'm gonna make/keep following targets:
all : imag-*
imag-% : ---- cargo build $(toml)
install : install-imag-*
install-imag-% :  ---- cargo install --force $(toml)
install-dev : install-dev-imag-*
install-dev-imag-% : imag-% prep ---- cp target/debug/imag-% out/
prep : ---- mkdir out
// remove doc target, is already done and may cause merge conflict
Please keep in mind that this is not actual code.
I don't know if the dependency of install-dev-imag-% is possible to do that way (I don't think so), so I might need to leave out this target, and do the copying in install-dev directly.
Does this sound about right?

**Comment by matthiasbeyer** [comment]
Your markup in the last comment is a bit... broken :smile: 

> // remove doc target, is already done and may cause merge conflict
> Please keep in mind that this is not actual code.

I'm not sure what you mean here.

> I don't know if the dependency of install-dev-imag-% is possible to do that way (I don't think so), so I might need to leave out this target, and do the copying in install-dev directly.

It is possible, but not as you posted it, IMHO. I guess you'll need to scan the `make` documentation on how to do this kind of thing.

**Comment by mario-kr** [comment]
Ok, there's this `$*` operator, which contains what is replaced by `%`, so `imag-todo` in the rule `imag-%` would lead to `$*=todo`, But I can't use this in the prerequisite, So I guess that's not the way :cry:

**Comment by matthiasbeyer** [comment]
#646 was merged.
