### ISSUE TITLE
travis build enhancements

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#625]
If we build `imag-todo` we only have to build `libimagtodo` for tests (`travis-cargo -q test`).

Also, we do not have benchmarks, so we could remove that (`travis-cargo -q bench`).

Maybe some other speed improvements could be added.

**Comment by matthiasbeyer** [comment]
Maybe we should refactor the build setup (for travis) to only build the required things. For example, if we change `libimagstore`, surely all the things have to be build. But if we change `libimagbookmark`, we do not have to build the world.

We should create a build script that

1. Fetches all crates in the repository that are affeced by the change. We could do this with some cargo stuff that gets us the dependency tree
2. Build all these crates and run the tests for them

That would improve build times a lot, I guess.

**Comment by neithernut** [comment]
Personally, at this point I'd begin splitting things into sub-repositories, each with it's own build setup.

**Comment by matthiasbeyer** [comment]
> Personally, at this point I'd begin splitting things into sub-repositories, each with it's own build setup.

Nope, I do not like that idea. This just creates overhead in multi-crate changes. After a `1.*` release, maybe. But not yet.

**Comment by matthiasbeyer** [comment]
I guess I can close this, we have better build times already (30-40 min).
