### ISSUE TITLE
Add more CI?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#676]
Would it make sense to add more CI servers?

I think of
- https://dependencyci.com/
- https://drone.io/

(drone does not yet support rust afaik, but maybe later on).

**Comment by neithernut** [comment]
Drone allows custom containers, which can contain the rust toolchain.

**Comment by matthiasbeyer** [comment]
@neithernut only in the self-hosted version.

**Comment by matthiasbeyer** [comment]
I don't think we need more CI anymore. Closing this therefor.
