### ISSUE TITLE
imag-notes/libimagnotes: Annotations

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#687]
Would be a good idea/feature to be able to

```
imag notes annotation --add example/entry
```

which does nothing more than create a note entry in the store, maybe named with a hash of the path of the entry to annotate. Then, the user can add a note (as usual) and afterwards, this note is linked to the `example/entry` via `libimagentrylink`.

Of course, other arguments for the `annotation` subcommand might be added:
- `--list` - list annotations for an entry (including some identifier for each, possibly the hash)
- `--delete` - delete annotations (by either selecting from a list or non-interactively by hash)
- `--show` - show annotations for an entry

possibly more...

---

The hash mentioned above should be unique for _each_ annotation. So using the `hash(path(file_to_annotate))` wouldn't be enough, as it would yield the same hash for two different annotations. The contents of the annotation is also not good, IMHO, as this would yield complex code when annotations should be immutable and an annotation should really be just the combination of `imag note` and `imag link`. So maybe the time when the annotation was created...

---

The args mentioned above might even be subcommands for the `annotation` subcommand themselves, each having arguments on their own.

---

The `annotation` subcommand is rather hard to type, so an alias should be provided. I would vote for `ann` or `anno`.

---

I guess this is not that hard to implement, as almost the complete infrastructure for this is already there, but it is not done in an eyeblink either.

---

@asuivelentine wanna have something not-so-small to work on? This could be something for you, if you want!

**Comment by asuivelentine** [comment]
Sounds like tagging and then this shouldn't be done by libimagnotes?!

**Comment by matthiasbeyer** [comment]
Not sure what you mean...

**Comment by asuivelentine** [comment]
I asked myself "when would i annotate a note...?" -> I would use it to search that special note by this annotation. Then this would be more or less the same like a tagging that note -> libimagentrytag?

Maybe I misunderstood your idea...?

**Comment by matthiasbeyer** [comment]
Maybe I'm misunderstanding _you_... an annotation should be simply just a `imag note add ... && imag link $new_note $entry_to_annotate`.

**Comment by matthiasbeyer** [comment]
As said in #733 we maybe should implement this in a new library and a new binary!

**Comment by matthiasbeyer** [comment]
Moving this to 0.3.0 as the `libimaglink::internal::LinkIter` feature will be in 0.3.0.
