### ISSUE TITLE
Store::metadata() ?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#688]
Should we provide a method to get some FS metadata of an entry from the store?

Something like [`File::metadata()`](https://doc.rust-lang.org/std/fs/struct.File.html#method.metadata) maybe? Maybe even an interface to this very function? So we can get data like creation-time and so on?

@TheNeikos, @neithernut what do you guys think?

**Comment by neithernut** [comment]
Not sure whether you mean the entry in the store or an actual piece of data referenced from the store, but it's a bad idea in both cases:
For metadata of a file containing a store entry: we want more abstraction of the store, not less. Consider storage in a git repo or, maybe, a database.
For files referenced in store entries: you can already query the metadata. The feature would be a mere convenience function which imo is out of the scope of imag.

**Comment by matthiasbeyer** [comment]
> For files referenced in store entries: you can already query the metadata.

Are you sure? I don't see how besides using the `StoreId`, parsing it to a `PathBuf` and then calling `metadata()` on it. You cannot access the `File` object under an `Entry`. Allowing to call `Entry::metadata() ` which then calls `File::metadata()` underneath would give us the possibility to get timestamps, which is IMHO a nice feature.

I see, though, that this might be out of scope.

**Comment by neithernut** [comment]
I did not talk about any file representing an entry in the sencence you cited (for those, the same argument I already posted applies: it denies you the possibility to use other means of storing entries).
In this segment, I was talking about the actual file you want to track with an entry. A media-file or a PDF document.

**Comment by TheNeikos** [comment]
If time is important one should save it in the file

**Comment by matthiasbeyer** [comment]
@TheNeikos that's indeed a good way to put it. So I guess I can close this issue and we conclude on the answer: **NO**.

**Comment by TheNeikos** [comment]
As an addendum one could maybe think about a default `created_at` or `updated_at` field that is created/changed respectively for a field should it become apparent that this is needed on a general basis. 
Since space is cheap and it doesn't bring much overhead it shouldn't be an issue other than bringing more code into the core.

**Comment by matthiasbeyer** [comment]
@TheNeikos nice idea. Care to open one?

**Comment by neithernut** [comment]
We don't even have a single user for this feature ATM.

**Comment by TheNeikos** [comment]
Yes we do, the TODO would benefit from it, as well as the Note binary
