### ISSUE TITLE
duplicate entries in links

### ISSUE THREAD

**Issue by mario-kr** [matthiasbeyer/imag#716]
Links in imag are always bidirectional, so if I make a link from `test1` to `test2`, Both entries get a value in the `links` array.
If I do this 2 times, There are 2 same entries. After a 3rd time however, the count doesn't increase.
Basically, it should be enough to inform the user that a link already exists, or just silently do nothing.
Also, info output is completely missing. When calling imag-link (successfully), there's no feedback whatsoever.

**Comment by matthiasbeyer** [comment]
Will add a test for this in #708

**Comment by matthiasbeyer** [comment]
I just found out that our checks do not work at all. Promising.

**Comment by matthiasbeyer** [comment]
#708 just got a fix for this issue.

**Comment by matthiasbeyer** [comment]
@mario-kr can this be closed? #708 was merged, so I guess the issue should've vanished.

**Comment by mario-kr** [comment]
ofc, yes
