### ISSUE TITLE
libimagrt: Option to compile without Store support?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#724]
This could be helpful for the `imag` binary, as we load a complete `Store` object, including registering hooks and so on... and we do not need it at all here.

I would therefor compile `libimagrt` for `imag` without store support.

@mario-kr what do you think?

**Comment by mario-kr** [comment]
I think that we just could use clap directly, without any `libimagrt` or special compilation. Wouldnt change too much in the code I believe, and we don't have any special "imag-functionality" in the binary either way.

**Comment by matthiasbeyer** [comment]
The point is that if we do not use the `Runtime` object we would need to duplicate some of the code from the `Runtime` clap setup (the debug flag, the verbosity flag, the config flag...).

Using the `Runtime` directly reduces code duplication but yields the overhead of having the whole `Store` opened (which indeed could even result in errors later when we do some filesystem-locking or such things).

**Comment by mario-kr** [comment]
Ok, but I'm not really sure how you want to achieve at compiletime, if I understood correctly.
Though the alternative would be a massive refactor.

**Comment by neithernut** [comment]
I'm honestly surprised that the store is initialized by `libimagrt`. It *kinda* makes sense, though.
Normally, I would suggest ripping out the initialization of the store and delegating it to the individual programs. It actually looks like the only real user of `libimagstore` is the `Runtime`. However, it also looks like initialization of the store does make up much of the code.

One possible approach would be to introduce a `libimagrtbase`, which contains all relevant pieces but does not depend on the store. `libimagrt` would contain a `Runtime` modification, which extends it by the store. This would be rather invasive, but I still wonder whether making `Store` support optional would be less invasive, or hurt readability too much.

**Comment by matthiasbeyer** [comment]
> Ok, but I'm not really sure how you want to achieve at compiletime, if I understood correctly.

The idea would be to have a flag on the crate which, if switched off, would result in no store-related code to be compiled into `libimagrt` - only the configuration foo and the commandline-setup foo would be in there, then.

> I'm honestly surprised that the store is initialized by libimagrt

The `Runtime` is supposed to be ... well, the runtime, having everything one needs for basically running imag binaries. So it only made sense to put all initialization there, including the `Store` object, which is quite complex to set up, yes.

> One possible approach would be to introduce a libimagrtbase, which contains all relevant pieces but does not depend on the store.

That'd be kinda clumsy IMO.

What I think about: The `Runtime` does not initialize the store by default, but one has to call `Runtime::init_store(&mut self)` which then does this. We can then use this function in the [`generate_runtime_setup`](https://github.com/matthiasbeyer/imag/blob/master/libimagrt/src/setup.rs#L13) function, so all crates get it by default. We then change the code in `bin/imag/src/main.rs` to _not_ use this function but build the `Runtime` object itself and simply not call `init_store()` - this way we would end up with just a little code modification and no overhead of a new crate or compiletime options and such.

One _small_ imperfection would be that the `Store` instance stored in the `Runtime` would be a `Option<Store>` and we would hard-`unwrap()` each time `Runtime::store()` is called, so we still return a `&Store` rather than a `Option<&Store>` - if there is a `None` we would simply `panic!()` **hard** and crash imag completely.

I would be fine with this, though I could understand if you are not.

**Comment by mario-kr** [comment]
> We then change the code in bin/imag/src/main.rs to not use this function but build the Runtime object itself and simply not call init_store()

not necessary.

**Comment by mario-kr** [comment]
>  if there is a None we would simply panic!() hard and crash imag completely.

Or instantiate the store in `Runtime::store` if needed.

**Comment by neithernut** [comment]
Ok, that's definitely less invasive. But now you gained one `unwrap()` which will end up as an unnecessary operation which the compiler will most likely not remove. And the need for the user to call `Runtime::init_store()` manually. IMO that's _more_ clumsy than my suggestion.

But whatever, looks like all the options are non-ideal. Also, @mario-kr may have a few ideas how to improve that approach.

**Comment by matthiasbeyer** [comment]
> Or instantiate the store in Runtime::store if needed.

No, that function is called ... many times during one imag run - we do not want to initialize a new Store object for each call, if that's what you mean.

@neithernut if we do not want to initialize the `Store` right when the `Runtime` is initialized, I see no other option (pun intended) than an `Option`.

**Comment by mario-kr** [comment]
I meant it singleton style:
```
pub fn store(&mut self) -> &Store {
  if store.is_none {
    store = Some(init_store(self));
  }
  return store.unwrap();
}
```

**Comment by matthiasbeyer** [comment]
@mario-kr That would need (as you already figured) a `&mut self` for the `store()` fn. But we cannot do that, as the `Runtime` is passed around immutably.

**Comment by neithernut** [comment]
@matthiasbeyer I know. That's why I proposed a completely different approach.

**Comment by mario-kr** [comment]
Well, We can always pass an additional flag to `generate_runtime_setup`

**Comment by matthiasbeyer** [comment]
Won't implement.
