### ISSUE TITLE
Continue-question on store overrides

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#753]
We should ask the user whether he wants to continue, if he overrides the configuration by commandline (if this isn't disabled... which could be done via a env variable - surely this won't work with a configuation setting :smile: )

This is rather easy. All the things are there already.

**Comment by neithernut** [comment]
Why would you do such a thing? It's a pretty normal thing to temporarily override the configuration via command line parameters. It also makes scripting cumbersome if you have to remember setting a "magic" environment variable, just to be sure the thing doesn't get interrupted (albeit that could also be resolved by determining whether the terminal is interactive or not).

**Comment by matthiasbeyer** [comment]
Discussion closed as: Feature Rejected.
