### ISSUE TITLE
Properly document link semantics

### ISSUE THREAD

**Issue by neithernut** [matthiasbeyer/imag#768]
The discussion on #765 showed that the semantics behind links are not as clear as they should be. The documentation should be expanded to explain these.

**Comment by matthiasbeyer** [comment]
The preparation is done. Feel free to file your PR.

**Comment by matthiasbeyer** [comment]
@neithernut Do you want to file a PR on this, or shall I write up some documentation for this?

**Comment by neithernut** [comment]
I would defer this until the link functionality was expanded by an (optional) name as suggested in #765.

**Comment by matthiasbeyer** [comment]
AFAICR we decided (in #765) to not alter the link functionality, but rather use intermediate entries with custom data in the header for adding semantics to links.

**Comment by neithernut** [comment]
Not exactly. We concluded that the *option* to name links (or associations) would be beneficial or even necessary for some (future) modules featuring item functionality dealing with some items' relations.

**Comment by mario-kr** [comment]
@matthiasbeyer I just came across something I wouldn't expect this way:
When I `imag link internal --list <some_entry>`, the external links are listed indirectly.
While I think it's perfectly fine to implement external links in such a way, I didn't really expect the internal link to the external-link-object to be listed.

**Comment by matthiasbeyer** [comment]
@mario-kr Could you please file a new issue about that?

**Comment by mario-kr** [comment]
the external-link being listed, or the inconsistency between external/internal? (or both?)

**Comment by matthiasbeyer** [comment]
Both!

**Comment by mario-kr** [comment]
But this certainly belongs here:
I just noticed that `imag link external --remove` does not take an argument; How do I know which external link I am deleting? May there only be one? When deleting is there some logic within external links to not delete external links, if they are pointed to by another entry?

**Comment by matthiasbeyer** [comment]
> I just noticed that imag link external --remove does not take an argument;

This is a bug, indeed.

**Comment by matthiasbeyer** [comment]
I'm marking this as done, assuming that it is documented enough already.
