### ISSUE TITLE
Rewrite: libimagdiary: FromStoreId -> Option<_> to use Result<_>

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#778]
https://matthiasbeyer.github.io/imag/src/libimagdiary/diaryid.rs.html#178

We should rewrite this to use `Result<_>` and return proper errors.

Would also be a nice experience for a beginner, though not a complete rust-beginner, I guess.
I guess this would also include some fixes in `imag-diary`, though I'm not completely sure.

**Comment by matthiasbeyer** [comment]
Note to self: Submitted to this-week-in-rust as easy issue that might be interesting for contributors.

**Comment by rnestler** [comment]
I would be interested in doing this one.

**Comment by matthiasbeyer** [comment]
@rnestler Wonderful! I'll mark this issue as "assigned", then. Feel free to ask any questions you might have!

**Comment by rnestler** [comment]
@matthiasbeyer awesome! First question: In rust nightly there is the [`TryFrom`](https://doc.rust-lang.org/stable/std/convert/trait.TryFrom.html) trait. Should I rewrite it to be similarly generic or just use a fixed `Error` type?

**Comment by matthiasbeyer** [comment]
@rnestler Just use the fixed error type from the [libimagdiary::error](https://matthiasbeyer.github.io/imag/libimagdiary/error/index.html) module. You might want to add a new [error kind in the libimagdiary::error::DiaryErrorKind enum](https://matthiasbeyer.github.io/imag/libimagdiary/error/error/enum.DiaryErrorKind.html) for that.

Note that we do not use nightly at all.
