### ISSUE TITLE
Refactor libimagentryfilter

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#779]
As the core functionality of this crate has moved to [the filters crate](https://crates.io/crates/filters) we can refactor this crate a bit:
- [ ] Move the tag filter foo to libimagentrytag
- [ ] Move the modules in `builtin` to the top-level
- [ ] Remove the `BoolFilter` - the `filters` crate has this already.

An easy task, but I guess boring for a rust beginner who wants to learn :smile:

**Comment by subhojit777** [comment]
I couldn't understand this "Move the tag filter foo to libimagentrytag" @matthiasbeyer 

I did `ack -w "foo" lib/entry/libimagentryfilter` but the output did not made much sense. Need help here.

**Comment by matthiasbeyer** [comment]
Because we are now [moving off of github](https://github.com/matthiasbeyer/imag/pull/1505) I'm closing this PR/Issue now. The reasons why we do this was described in a [blogpost](https://imag-pim.org/blog/2018/06/10/off-of-github/). Feel free to resubmit this PR/Issue via the mailinglist.
