### ISSUE TITLE
imag mv

### ISSUE THREAD

**Issue by neithernut** [matthiasbeyer/imag#785]
Consider an eBook or article which you just downloaded to a "Downloads", "tmp" or "new" directory. After a while, you may reference it using an imag entry, e.g. when working on a paper. You may, however, still be unsure where to store/archive the paper. Having some directory structure, you might defer the decision until you have read the contents. Maybe you change the location or directory structure you use for storing books and articles. You may want to move the book at some point in time. 

Currently, you'd instruct `imag` to "re-find" the book and update the corresponding entry. However, it would be nice to also be able to do this proactively, using `imag`, updating the entry as you move the file. A sub-command `imag mv` would allow users to do this. Additionally, `imag mv` might also be used to move entries within the store.

**Comment by matthiasbeyer** [comment]
Jup. The re-find functionality can be refactored to support this rather easily I guess.

I will move this as "optional" in the 0.3.0 release, as the 0.2.0 is almost completed and I would like to get it done soonish. Feel free to implement as soon as you can, if you wish, so we might have it in 0.2.0 already.

**Comment by neithernut** [comment]
Btw, this functionality should also be exposed as an internal interface so modules can move stuff around, too.

**Comment by matthiasbeyer** [comment]
Please also note that an `imag mv` command would be related to `imag ref` (with flags, possibly), so we should be careful about doubling functionality.

**Comment by neithernut** [comment]
One could implement `imag mv` as an alias.

**Comment by matthiasbeyer** [comment]
> Btw, this functionality should also be exposed as an internal interface so modules can move stuff around, too.

The `Store` already supports moving entries, so that's less of an issue. It's about to be tested in one of my PRs, too.

> One could implement imag mv as an alias.

More or less yes.

**Comment by matthiasbeyer** [comment]
We also should be careful not to re-implement the `mv` command itself. Maybe we can actually _use_ the `mv` command in the background.

**Comment by matthiasbeyer** [comment]
>> Btw, this functionality should also be exposed as an internal interface so modules can move stuff around, too.

> The Store already supports moving entries, so that's less of an issue. It's about to be tested in one of my PRs, too.

Just to be clear: The Store has functionality for moving things around. I still think something like `libimagentrymove` has to be written, because the Store itself has only a rather low level interface for moving things and one might consider some things when moving entries around (for example links).

`libimagentrymove` won't be complex, though.

**Comment by matthiasbeyer** [comment]
`imag mv` is implemented for moving entries inside the store. What you specified in the init comment about moving things on the filesystem and imag keeping automatically track: Yes, that's indeed a nice idea, but I'll postpone this until later.
