### ISSUE TITLE
Properly document trait FoldResult

### ISSUE THREAD

**Issue by neithernut** [matthiasbeyer/imag#796]
A discussion in #777 demonstrated that the `FoldResult` is rather confusing for some people. Looking at the file containing it (`libimagutil/src/iter.rs`), the documentation is rather sparse. It should be expanded. In particular, the difference to `itertools::fold_results()` should be emphasized.

**Comment by matthiasbeyer** [comment]
I marked this as `complexity/medium` as it might not be that obvious to beginners how this works, so it would be better to have someone with a bit of Rust experience documenting this.
