### ISSUE TITLE
StoreId: cmp without base?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#806]
As #805 shows, we run into issues because `StoreId` objects are compared with and without base.

Maybe we should adjust the implementation to compare only the local part. We lose the ability to have multiple stores open at the same moment in time. I don't think we need that ability, but I'm not sure.

@TheNeikos and @neithernut what do you think? If we agree, this issue is really easy to implement, IMHO.

**Comment by neithernut** [comment]
Another possibility would be to compare the bases only if neither is `None`.

Anyway, I think in multi-store scenarios, it pretty much depends on how you handle the overall situation: if you want to use multiple stores transparently, you don't need to distinguish between `StoreId`s with different bases except some cases --e.g. when you move things from one store to another; and this case would qualify as an exception where a custom, inline comparator would be acceptable imo.

**Comment by matthiasbeyer** [comment]
Well then... i guess we should remove the `derive(PartialEq, Eq)` and implement these traits to compare only the `local` part.
