### ISSUE TITLE
Iterator for Iterator<Item = Result<T, Error>> tracing

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#813]
That would be a rather nice playground for some beginners to play around with iterators.

What I want is basically a generic iterator that is able to trace (as in `libimagerror::trace::*`).

I want to be able to call

```rust
iterator.trace_unwrap(); 
// The above is a: Iterator<Item = Result<T, Error>> -> Iterator<Item = T>
// which `trace_error()`s the errors and then filters them out in the output iterator

iterator.on_err(|e| debug!("Error happened: {:?}", e))
// The above returns the iterators items unmodified, but calls the closure
// on each error from the iterator

iterator.unwrap_with(|e| debug!("Error happened: {:?}", e))
// The above is a: Iterator<Item = Result<T, Error>> -> Iterator<Item = T>
// which calls the passed closure for each `Error` and filters them out in the output iterator
```

Function names are just made up and one could probably come up with better names.

---

I mark this as `complexity/easy` - it's not for complete rust beginners, though, but I guess it is good for someone who already knows Rust a bit and wants to play with traits and Iterators.

All the work will be done in `libimagerror`, in a new submodule `iter`, I guess.

Will submit this issue to TWIR.

**Comment by Thiez** [comment]
Would something like [this](https://github.com/Thiez/imag/commit/1065f8ad33e96d5b3bc03c9162039d9be96176fb) (unpolished, no documentation) represent the semantics you have in mind?

**Comment by matthiasbeyer** [comment]
@Thiez this looks really good, yes. Before you submit a PR, please make sure you do have a feature branch and do not submit a PR from master, please!

Besides that, I'm looking forward to see your PR and I'm eager to see what the CI tells us on this! :smile:

**Comment by matthiasbeyer** [comment]
Whops, should close this :smile:
