### ISSUE TITLE
Release strategy discussion for 0.2.0

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#814]
So here is how I will do the release (finally I have a plan).

---

Things that can go into the `master` branch:

- [x] Set all the meta-information in all crates
- [ ] Make sure things build

Then I will create a `release-0.2.0` branch and:

- [ ] set the dependencies of the crates to use the crates.io package, not the local path ( @TheNeikos will this be possible? When `cargo publish`ing a crate, it checks whether all crates are available on crates.io, am I right? So I would need to publish them in the right order, am I?)
- [ ] Publish the crates on crates.io
- [ ] Tag the published commit as `v0.2.0` and
    - [ ] push that tag to github and all other remotes
    - [ ] remove the `release-0.2.0` branch, also from the remotes

---

I'm not sure whether this works, hence this issue to discuss things. Would be nice if @TheNeikos (and others of course) could have a look and tell me what will do and what won't work.

**Comment by TheNeikos** [comment]
I don't know whether it cheeks on crates.io, it does check if it can be built tho

**Comment by matthiasbeyer** [comment]
Yep, that's what I though. And that's the problem, as far as I can see: We need to release the crate which sits at the bottom of the dependency tree first and then go up the tree. This is a hell of complexity to figure out, IMHO, and it shouldn't be that complicated, really.

I know about `cargo-graph` and so on, yes... but it is not scriptable I guess...

**Comment by TheNeikos** [comment]
>  However, crates that use dependencies specified with only a path are not permitted on crates.io.
From http://doc.crates.io/specifying-dependencies.html so I guess it won't work?

**Comment by matthiasbeyer** [comment]
That's the point: My idea was to release _all_ crates on crates.io, and set the dependency specification in my `release-0.2.0` branch to use the crates.io version of the dependency - so it would work.

But as said, I would need to go from the bottom of our dependency tree up to the top, _by hand_.

**Comment by TheNeikos** [comment]
It doesn't seem all too bad :? just do:

    while true; do
        for i in *; do
            pushdir $i
            cargo publish
            popdir
        end
    end

:P

**Comment by matthiasbeyer** [comment]
That _won't work_ because a crate depends on the crates.io version of another crate which _might not be on crates.io yet_.

I cannot `foreach` as `imag-store` depends on `libimagstore` and if the latter is not yet `cargo publish`ed yet, the `cargo publish` in `imag-store` fails as the dependency cannot be fetched!

**Comment by TheNeikos** [comment]
Yeah, and then it goes to the next crate, tries there until it finds one which works and it loops back and tries them all again! Eventually they will all have been uploaded :v

**Comment by matthiasbeyer** [comment]
hm. Could work, but one should also do some bookkeeping which things have already been published, so we do not `cargo publish` them again.

**Comment by matthiasbeyer** [comment]
From the help:

```
$ cargo publish --help
...
    --no-verify              Don't verify package tarball before publish
...
```

**Comment by TheNeikos** [comment]
Ew :disappointed:

**Comment by matthiasbeyer** [comment]
Yeah, it is really not the ideal solution, I see that.
