### ISSUE TITLE
Rewrite bash-script tests in Rust

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#830]
As we have the test infrastructure in the imag-store, we can rewrite the tests in rust, IMO.

The following files (as of master at ) have to be rewritten:

```
./imag-link/tests/link-test.sh
./imag-link/tests/utils.sh
./imag-store/tests/001-create_test.sh
./imag-store/tests/utils.sh
./imag-store/tests/003-delete_test.sh
./imag-store/tests/002-retrieve_test.sh
./tests/utils.sh
```

I add the "easy" tag here, I think this is rather easy to do for a not-complete-rust-beginner.

**Comment by matthiasbeyer** [comment]
The Makefile can be adapted as well, then.

**Comment by irobert91** [comment]
Hi! I would like to work on this.

I have a question though:
I believe that it is expected for the tests to be pretty much just translated from bash to Rust. If so, what would be a good way for the prep and cleanup phases to be invoked for each test? I am referring to these:
https://github.com/matthiasbeyer/imag/blob/master/tests/utils.sh#L82
https://github.com/matthiasbeyer/imag/blob/master/tests/utils.sh#L49

I was thinking about using similar logic, of creating a `fn` for each test and then invoking them all, like `invoke_tests` does, but this doesn't feel Rusty. Would it be fine to just call Rust versions of `prepare_store_directory` and `reset_store` at the beginning and end of each test?

**Comment by matthiasbeyer** [comment]
Hi. Awesome that you want to tackle this! :heart: 

First of, I'm pretty sure we don't want to use rust to call an imag binary, so that'd be a major difference from the bash tests. We want the tests to be in the binary itself, though I don't know whether you can have `#[test]`s in a rust _binary_.

The second thing:

You actually don't need `prepare_store_directory` and `reset_store` to be translated to Rust because the Store backend itself does automatically use an in-memory filesystem instead of the real filesystem when running the tests. So there won't be a possibility to test the hooks (for example the git hook), but I'm even not sure whether the hooks was a good idea. Maybe for debugging and simple assertions, but not for things like git tracking. So no problem leaving this out, actually.

Feel free to ask more questions! :+1:

**Comment by irobert91** [comment]
I see. I thought that you would still want to have integration tests, similar to the current ones, so I was going to use `std::process::Command` to call the `imag-link` and `imag-store` binaries.
But as I understand now, you would rather prefer to have unit tests? Would the new tests cover the same parts as the bash tests and only that?
I'm not sure I understand the part about the tests being in a binary. Wouldn't it be enough to have a `#[cfg(test)]` mod?

**Comment by irobert91** [comment]
I think I understand now. You mean binary as opposed to library. It is possible.
I will try to open a PR soon.
Thanks for all the answers!

**Comment by matthiasbeyer** [comment]
> One more thing: should there be 2 separate PRs for imag-link and imag-store as mentioned in CONTRIBUTING.md?

Yes that'd be nice.

If you have to do infrastructure work (common functionality for the tests) you are welcome to implement them in a new library crate (something like "libimagbinarytesting" or something) and base your other two PRs on the PR for this library - but I'm rather sure you don't need to implement common functionality for testing...

**Comment by irobert91** [comment]
I started with the `imag-link` tests and am a bit confused. As far as I can tell, the thing that could be unit tested is https://github.com/matthiasbeyer/imag/blob/master/imag-link/src/main.rs#L151, but then there already are unit tests for `add_internal_link` here https://github.com/matthiasbeyer/imag/blob/master/libimagentrylink/src/internal.rs#L588.

Should I actually be writing tests for `handle_internal_linking`? If so, could you give me some indications regarding how to set up the `Runtime` properly? I believe that I would need to somehow configure it, (create and) populate a `Store`, create test entries and then mock the cli subcommands and args. Does this make sense or am I on the wrong track?

**Comment by matthiasbeyer** [comment]
> Runtime [...] I believe that I would need to somehow configure it, (create and) populate a Store, create test entries and then mock the cli subcommands and args. Does this make sense or am I on the wrong track?

Yep, that's right. I'm really tired by now, will answer more detailed tomorrow (I'm goig to a conference tomorrow, so there'll be plenty of time tomorrow...)

**Comment by irobert91** [comment]
@matthiasbeyer is it sufficient to use [`generate_runtime_setup`](https://github.com/matthiasbeyer/imag/blob/master/libimagrt/src/setup.rs#L32) to create the `Runtime`?

It seems to me like the cli arguments must be passed through the cli itself and cannot be mocked since [`Runtime::new`](https://github.com/matthiasbeyer/imag/blob/master/libimagrt/src/runtime.rs#L77) uses [`clap::App::get_matches`](https://docs.rs/clap/2.24.2/clap/struct.App.html#method.get_matches) which gets the matches from [`std::env::args_os`](https://doc.rust-lang.org/std/env/fn.args_os.html). We could achieve this by using [`get_matches_from`](https://docs.rs/clap/2.24.2/clap/struct.App.html#method.get_matches_from) instead, but I think that it would need some considerable refactoring, although I'm not sure.

Also, could you tell me what is be best way to configure the `Runtime` in this case? As far as I can tell, it needs a toml file, but is having a config file ideal just for some unit tests?

**Comment by matthiasbeyer** [comment]
We could refactor the `Runtime::new` function to not use the ``App::get_matches`` fn, but a wrapper which can be replaced (for testing purposes) by a mockup. Your idea sounds good as well!

I'm not sure how much boilerplate/work this would include.

Having a _file_ for the configuration is not that great, IMO. We could include a TOML directly in the build artifact for this, though. We would then need to refactor the config-loading process out.
