### ISSUE TITLE
Focus-Shift: imag.rb

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#846]
This is mainly the discussion-platform and description of the [0.3.0 milestone](https://github.com/matthiasbeyer/imag/milestones/3).

---

# Focus-shift: imag.rb

Why: [Summed up here](https://beyermatthias.de/blog/2017/01/17/whats-coming-up-in-imag-22/)

TL;DR: Remove own integrations, build Ruby-Gem out of core libraries,
because bootstrapping tools/integrations in Ruby is faster.

- [x] Remove:
    - [x] imag-bookmark
    - [x] imag-counter
    - [x] imag-diary
    - [x] imag-mail
    - [x] imag-todo
    - [x] libimagbookmark
    - [x] libimagcounter
    - [x] libimagdiary
    - [x] libimagmail
    - [x] libimagnotification
    - [x] libimagtodo

- [x] Keep
    - [x] imag-link
    - [x] imag-ref
    - [x] imag-store
    - [x] imag-tag
    - [x] imag-view (though a Ruby tool might come up with way better functionality)
    - [x] libimagentrytag
    - [x] libimagentryview
    - [x] libimagerror
    - [x] libimagref
    - [x] libimagrt
    - [x] libimagstore
    - [x] libimagstorestdhook
    - [x] libimagutil

- [ ] Keep maybe (though there might be a better/more flexible impl in Ruby at some point):
    - [ ] imag-notes
    - [ ] libimagnotes

- [ ] Add build infrastructure for Ruby
  - [ ] Testing of the Ruby-Gem
    - [ ] rspec?
    - [x] Unit tests?
  - [x] CI infrastructure

- [ ] Remove maybe (if not used elsewhere):
  - [ ] libimagtimeui
  - [ ] libimaginteraction

## And then...

Build `imag.rb`, a Gem to talk from Ruby to `libimagstore` (+`libimagerror`
and other foundation-libs) and later also to `libimagentrytag` and
`libimagentrylink`).

After that is done, we have to
- [ ] re-check all issues in the upcoming milestones whether they still apply to the codebase.

**Comment by mario-kr** [comment]
I'd like to suggest/note a few things here:
* You forgot `imag-todo`, which probably goes onto the "to-delete"-list
* Maybe you'd want to keep a tool like imag-counter and/or  imag-notes as an example implementation of a backend in Rust
* Probably a restructuring of the releases/milestones. (which you also kind of mentioned)
I guess this will somewhat replace the generic scripting interface (lua, ...)?

**Comment by matthiasbeyer** [comment]
> You forgot imag-todo, which probably goes onto the "to-delete"-list

Yep, fixed. Thanks.

> Maybe you'd want to keep a tool like imag-counter and/or imag-notes as an example implementation of a backend in Rust

Yep, that would be a reason to keep `imag-notes`. I'd rather keep `imag-notes`, as I see no value in `imag-counter`.

> Probably a restructuring of the releases/milestones. (which you also kind of mentioned)

Is already done. 0.3.0 is "imag.rb" now, 0.4.0 contains all issues of 0.3.0 and 0.5.0 contains all issues of 0.4.0. Of course, after 0.3.0 is done, we have to reiterate on 0.4.0 and close all the things that have become irrelevant (issues for removed stuff, of course).

**Comment by matthiasbeyer** [comment]
@mario-kr (and maybe @TheNeikos) Can you have a look at the updated TODO above? Especially the point `Use in `imag-ruby` gem (not sure whether this could be in the next release):` - I'm not sure whether I should release the `0.3.0` imag release for the `libimagstore` ruby bindings and the _next_ version (0.4.0) for the enhancements with `libimagentry{tag,...}`.

I _guess_ the latter would be nice, as we would release more often. But I'm not sure whether this is the right thing to do.

What I think of:

* If I release 0.3.0 as soon as possible, people can start playing with the Ruby bindings directly (maybe even next week).
* If there are things fucked up in my code I could release 0.3.1 as bugfix-release.
* When 0.4.0 comes out, people get more awesome things directly in the ruby bindings.

On the other hand, having a full battle-ready ruby library for imag directly with 0.3.0 is a neat thing (so all the nice things of `libimagentry{tag,...}` already included.

I tend to release 0.3.0 as soon as possible. But I'd love to have a second (third?) opinion on that!

**Comment by mario-kr** [comment]
I approve of the early 0.3.0 release.

**Comment by matthiasbeyer** [comment]
Okay. I moved milestone-issues once more (0.5.0 -> 0.6.0, 0.4.0 -> 0.5.0) and opened issues for the library adaptions in milestone 0.4.0.

I want to include the ruby tests in this release, which is the last point in this very issue.

**Comment by matthiasbeyer** [comment]
This was removed from the 0.3.0 milestone as it is a too large blocker and the whole infrastructure is not mature enough yet.

So we focus on other things and get this done another time.

**Comment by matthiasbeyer** [comment]
I'm not longer interested in a scripting API as I will focus on the command-chaining, which gives us language-interop via JSON export of the store. This way we get all the languages instead of just one.

See #956
