### ISSUE TITLE
suggestion: contact ledger-cli@googlegroups.com regarding the ledger module

### ISSUE THREAD

**Issue by johannesjh** [matthiasbeyer/imag#851]
Sorry for doubleposting, but I accidentally posted the following text to issue #10, which is closed, so I wasn't sure if you'd see the message. Here goes...

Hi Mattias, I think you should consider discussing your ideas at ledger-cli@googlegroups.com. I have myself asked a few questions there and I always got friendly, helpful and motivated answers.

As a sidenote, I stumbled upon the imag tool when I was searching for a way to integrate (link, track...) beancount data with todos or even workflow-oriented data for tracking invoices. Beancount proposes to use links or tags to group transactions related to an invoice together. It also has a `document' statement to link to PDFs, e.g., to the invoice sent to the customer. But, from what I know, it does not have features for tracking the status of an invoice (e.g., draft, to be payed, payed, closed, cancelled etc). Would this use case be something where imag can provide value by integrating something like taskwarrior with beancount?

Johannes

**Comment by matthiasbeyer** [comment]
I will close this and continue discussion in #10, which is marked as `reopen-later`.
