### ISSUE TITLE
Remove ruby dependencies in build to get 0.3.0 out?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#928]
We should remove the ruby dependency in the build (and eventually the complete `libimagruby`) to get the release out.

The 0.3.0 release is 1 month overdue already and we really should get it out now. But the 0.3.0 release was all about the ruby scripting API as well... so there's that.

Can I have an opinion from @TheNeikos and @mario-kr ? Get 0.3.0 out now and fix `libimagruby` (and the build) later, or wait until it is fixed?

If released now, 0.3.0 contains not very much things. All in all just refactoring, some new functions in the libs and mostly a lot of `imag-*` programs removed.

**Comment by mario-kr** [comment]
We're below 1.0.0, so do whatever you want. As this statement is not useful: imo you could wait for libimagruby.

**Comment by matthiasbeyer** [comment]
@asuivelentine I value your opinion, too!

**Comment by matthiasbeyer** [comment]
I removed `libimagruby` now from the master branch, so we can get a green master. I will wait with the release, though, until `libimagruby` can be included in the release.

Hopefully #925 is the last PR we need to fix travis...

**Comment by matthiasbeyer** [comment]
I guess I will remove the ruby libraries from the 0.3.0 release and instead go with some other things for the ruby release.
