### ISSUE TITLE
Rethink libimagstorestdhook?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#950]
We should rethink the hook infrastructure.
Do we really need it?

* Integrity checks like the linking-check could be made available through a imag-* binary (for example `imag link --integrity-check`)
* git functionality could be made into a CLI App: `imag git`
* Debugging hooks could be moved to the store codebase
* The complexity of the store implementation would be reduced _heavily_!

So where are the advantages of the hooks? I don't see any right now. The only thing one could argue about is that they are automatically executed on CRUD actions.

**Proposal**: Remove hook functionality.

@mario-kr @TheNeikos @neithernut @asuivelentine comments?

**Comment by neithernut** [comment]
We originally conceived of several kinds of hooks which are not covered in your list, e.g.:
 * Hooks for encryption/decryption of data
 * Hooks which automatically add additional (module specific) data to an entry
 * Hooks which do module specific sanity checks

**Comment by matthiasbeyer** [comment]
> Hooks for encryption/decryption of data

This isn't our domain. The user should encrypt the store via filesystem encryption, IMO.

> Hooks which automatically add additional (module specific) data to an entry

It is easier to implement this in the respective modules itself rather than via the (rather complex) hook system, IMO.

Also, I have plans/ideas to move imag to support command-chaining (think of `imag entry new | imag tag add "foo" | imag category add "sports" | imag add content --from stdin | imag entry write --to /some/store/path`)

Adding data implicitely with this would cause  confusion and therefor do more harm than good, that's why I'd rather opt for removing hook support.

> Hooks which do module specific sanity checks

I'd ask the user to do these explicitely rather than doing them implicitely.

**Comment by neithernut** [comment]
>> Hooks for encryption/decryption of data
>
>This isn't our domain. The user should encrypt the store via filesystem encryption, IMO.

Well, back than we had a different idea. And that applies to the other cases I mentioned, too.

**Comment by matthiasbeyer** [comment]
I just re-read some of the history from back then. My point stands, though: The store codebase is way to complex with all the hook stuff. The problem is also that the hooks are rather limited.

Re-introducing a hook-like system should work in another way, IMO:

It should wrap the store implementation into a `StoreLike` and execute hooks _before_ actually calling into the store. The interface should be the same as with the store, of course.
This way, we can keep the store codebase itself clean. Also, this wrapper trait (that's what I think of) could be implemented in the libimagstore codebase itself, so we have less boilerplate.

The thing is, with the current hook implementation, that _each_ binary builds the complete (and complex) hook system for the runtime. If we chain commands (`foo | bar | baz`) we have _a lot_ of overhead for this. With the wrapper idea, one could execute hooks explicitely (think of `imag entry new | imag hook --exec --read-from stdin --print-to stdout | imag entry write --to /foo/bar` or something less complex), which would reduce overhead a lot and give us way more flexibility.

Thank you for your points anyways! This way I thought of alternatives!

Anyways, I will merge the PRs I submitted for this (#951, #952, #953 and #954)!
