### ISSUE TITLE
Imag command chaining

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#956]
I'm heavily thinking about redesigning imag a bit to be able to do command-chaining (with pipes as one does with the shell), so that things like

```bash
imag entry new | imag tag add foo | imag category add baz | imag entry add-content --from /tmp/text | imag entry write --to /some/store/place
```

are possible.

I'm thinking how to implement this without having to change a lot of the codebase

# Store support for this

We could easily implement this with the store, as far as I know. This would then happen using a known structured data format for data passing. I would use JSON for this. 

## Store interface changes

The basic idea is to change the `create()`, `delete()`, `get()` and `update()` function to not get a `StoreId` but a `EntryIdentifier` which is

```rust
enum EntryIdentifier {
   Id(StoreId)
   StdIn // for `update` and `delete`
   StdErr // if needed
   StdOut // For `get` and `create`
```

`StoreId` would `impl Into<EntryIdentifier>`, so the current use of the store won't change at all (maybe a `into()` call here and there).

With a non-`EntryIdentifier::Id(_)` passed, the store would use the `stdin`/`stdout` to read/write entries.

The data format which is proposed below could be processed by the already implemented `imag-*` tools without much modification. The `Store::*()` calls would be altered a bit. A tool can also easily check whether it should read from stdin/write to stdout: if the `--id`/`--path` argument is not passed (the argument which defines which store entry should be altered), the data is passed via pipe.

## JSON for passing objects around

The JSON format would be pretty simple:

```json
{
    "version": "0.3.0",
    "pipe": [ {
            "module": "libimagentry",
            "call": "imag-entry create"
        },
        {
            "module": "libimagentry",
            "call": "imag-entry create"
        }
    ],

    "entries": [
        {
            "header": "// header goes here. TOML <=> JSON is possible AFAIK",
            "content": "// content... "
        }
    ],
}
```

### Explanation of the fields

The `version` field could be used for knowing which version of the store is required to be able to process this structure correctly.

The `pipe` field just popped into my mind when writing this - it could be used so we know what transformed the entries already.

The `entries` field then contains a list of entries as JSON objects.

### Intermediate store

A variant of the above data format would be that the `entries` field does not contain a JSON-Array, but a JSON-object, where the keys are (baseless) `StoreId`s:

```json
{
    "entries": {
        "/some/id": { "header": "", "content": "" },
        "/some/other": { "header": "", "content": "" }
    }
}
```

This way, the `Store` could act on them without the `imag-*` implementation knowing. It would give us even more flexability.

This would also emit the need for `imag entry write --to /foo/bar` as the initial `imag entry new` call would need to specify where the entry should land: `imag entry new /foo/bar` - sanity checking against the _real_ store on the filesystem could happen there (and duplication be denied via flag,... possibilities are of course endless here).
The final call would then be `imag store apply --from stdin` or something like that, to apply the "Intermediate JSON Store" to the real on-filesystem store.

# Caveats

If applying of the changes to the filesystem-store fails, the contents of the passed-around JSON should be either written to `/tmp` or a similar location, or be printed to CLI (depending on their size), so no data is lost.

# Drawbacks

Of course this would introduce a _lot_ of JSON/structured data parsing at runtime. But I guess processing a few KB of JSON is no problem even for small computing units like RPI or something.

I cannot think of more drawbacks from the top of my head.

**Comment by matthiasbeyer** [comment]
@neithernut @asuivelentine @mario-kr @TheNeikos and @irobert91 This is a RFC, I'd love to hear what you guys have to say...

**Comment by neithernut** [comment]
Chaining support the way you proposed would make things ambiguous for the user. If I understand correctly, simple omitting a store id in an invocation makes a regular command a chained command. Now consider a regular user simply forgetting to pass that parameter.

Furthermore, the proposed implementation doesn't necessarily work out, either:

    enum EntryIdentifier {
        Id(StoreId)
        StdIn // for `update` and `delete`
        StdErr // if needed
        StdOut // For `get` and `create`
    }

If you want to chain the command, you may need to both read and write an entry. For example, you want to pipe it through some command, altering it. Your version of the `EntryIdentifier` lets you only either read or write an entry. Also, you never ever want to write an entry to `stderr` during normal operation. `stderr` is used for user notification, not for payload.

**Comment by matthiasbeyer** [comment]
> Chaining support the way you proposed would make things ambiguous for the user. If I understand correctly, simple omitting a store id in an invocation makes a regular command a chained command. Now consider a regular user simply forgetting to pass that parameter.

I'd then opt for implicitness until the 1.0 release and from then on only support the chaining variant by default, and the "one-shot-on-the-store" via an explicit parameter... or something like that. Maybe even sooner, depending on how well it works.

> If you want to chain the command, you may need to both read and write an entry.

You did not read carefully enough or my explanation was not that good: Reading an entry would be done via `store.get(EntityIdentifier::Stdin)` and writing it via `store.update(EntityIdentifier::Stdout)`.

Although, now that you mention it, we have then to be carefull with our drop semantics, ... when the store gets dropped (the in-memory store which is read from CLI), the store has to serialize and print it to stdout.

> Also, you never ever want to write an entry to stderr during normal operation. stderr is used for user notification, not for payload.

Indeed.

**Comment by matthiasbeyer** [comment]
Some more notes:

### Data-Backups

I'm not sure whether writing a backup of the file to `/tmp` or something would be beneficial for anyone. This is mainly because of two reasons:

If we create a new entry in the first command (think `imag entry new`), the entry is not special at all... if things fail the user might simply call the command again

If we read an entry in the first command and some command in the chain fails, the entry is not altered in the store, is it? So calling the chain again would do!



What we _can_ do, though, is dumping the JSON to a file all the time. As in "the command X in the chain reads the JSON, modifies it and dumps it to disk before writing it to stdout. This would give us the possibility to re-run parts of a chain if a command in between fails. Think like this:

```
a | b | c | d | e | f | g | h
```

where `a` reads from the store, `b..g` do transformations and `h` writes back to the store. If `e` fails but the JSON is persisted in `d`, we can run `cat $backup | e | f | g | h`.

### Filter possibilities

With the idea of having `stdin` and `stdout` as source and sink, we can do things like that:

```bash
imag entry new --at /music/metal | \# creates a new entry at /music/metal
  imag entry add --at /music/trance | \# creates a new entry at /music/trance
  imag filter --name-glob metal --do 'imag tag +metal' | \#for each entry where the name contains "metal", execute "imag tag"
  imag filter --name-glob trance --do 'imag tag +trance' | \#for each entry where the name contains "trance", execute "imag tag"
  imag category add "music" | \# add category "music" to each entry
  imag edit --all-in-one | \# Call the Editor for all entries (all in one editor: vim $store/music/{metal,trance})
  imag entry move --from /music/metal --to /music/heavymetal \# Move entry before persisting
  imag persist # write things to the store
```

or, if available, use bash features to do things like shown above.

**Comment by sharethewisdom** [comment]
I think it's worth referencing FreeBSD's [libxo](https://github.com/Juniper/libxo). I'm surprised that there doesn't seem to be a similar library for linux :disappointed:

**Comment by neithernut** [comment]
Why shouldn't it work on Linux?

**Comment by matthiasbeyer** [comment]
@sharethewisdom Thanks for mentioning this, I'll definitively check this out!

**Comment by sharethewisdom** [comment]
@neithernut good question, I think no-one actually tried. I haven't seen it packaged anywhere.

[This answer](https://unix.stackexchange.com/a/365406/65962) made curious in the first place... Maybe standard output could also be rendered locally by a client receiving json over the network, using a terminal like [mosh](https://mosh.org). Parse-ability would certainly benefit the future of some of the `{core,find,patchdate,more,diff,inet}utils`!

**Comment by matthiasbeyer** [comment]
# Rethinking command chaining

So, I recently had a discussion with @TheNeikos (whom I'd like to ask to review this) about command chaining and after thinking a bit, I think it would be possible in a nice way.

## Requirements

Steps to do before command chaining can be implemented:

- [ ] refactor `libimagrt` to hold all environmental information one might need.
    * This explicitely includes `stdin`/`stdout`. These resources should be made available to imag code via `libimagrt`.
    * `libimagrt` should also hold interactive functionality, or at least an interface to it. Obtaining a interactive UI to the user should fail if `stdin` is not a TTY. Therefore, `libimagrt` should provide a `--interactive | -I` commandline switch which automatically causes `libimagrt` to error out if `stdin` is not a TTY but the `--interactive` switch is passed. Interactive functionality should be obtainable through `libimagrt` only. This will blow up the size of `libimagrt`, of course, as we basically include `libimaginteraction` into it. If `stdout` is not a TTY, logging is still possible to `stderr`, so this is no problem for us.
- [ ] rewrite how `libimagrt` loads the `Store`:
    * If `stdin` is a TTY, the `Store` is loaded from FS
    * If `stdin` is not a TTY, `stdin` is read and be assumed to be a JSON object holding the `Store`. So the Store is read from a pipe
    * If `stdout` is a TTY, the store is written to disk
    * If `stdout` is not a TTY, the Store is serialized and written to STDOUT.
    with this we get chaining "for free".

## Implementation

If the store has to be written to stdout or be read from stdin, this requires `libimagrt` to re-set the store backend at runtime if before reading the store or before closing the store.
This is complicated to implement, especially in the case where one of `stdin`/`stdout` is not a TTY but the other one is (because then swapping happens during the lifetime of the Store).

Maybe there is a way to abstract this inside the store? I'm not sure how this could be done.

**Comment by matthiasbeyer** [comment]
With #1315 and #1325 merged, we now have to find a way to serialize and deserialize the `Store`, basically.

Maybe we should implement `Serialize` and `Deserialize` on it, or rather its internal cache. I'm not sure whether this is a good idea, though.

**Comment by matthiasbeyer** [comment]
The more I think about it, the more I like it.

We could implement serialization on the entry type (https://serde.rs/data-format.html) for de/ser it to tge format we want on disk and use serde_json by deriving.

We should, though, carefully explore whether this is possible (because we use `toml::Value` directly internally, which might complicate things).
