### ISSUE TITLE
Redefine build process

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#986]
Cargo is able to build workspaces, so we do not need the `Makefile` anymore I guess.

We should redefine the build process therefor. And we should update the documentation in the `README` of course.

@mario-kr you were heavily involved in the build process things... wanna tackle this in your spare free time? :smile: 

---

I'm not assigning a milestone here because it is not that important. If we get it done before 0.3.0 - fine! If not - also fine!

**Comment by mario-kr** [comment]
please check if youre still able to build single libraries/binaries using workspaces. To my knowledge (which might be outdated or even completely wrong, no guarantees on that), thats not possible.
Though the Makefile may be cleaned up a bit for the {check,install,build,build-release,update} everything kind of commands.
I actually thought i already proposed such a clean up and/or made a PR for it?

**Comment by mario-kr** [comment]
The Makefile tells me that clean, update and outdated have been optimised in this way
